domstolene/designsystem

components/src/components/OverflowMenu/OverflowMenu.tsx
components/src/components/OverflowMenu/OverflowMenu.types.tsx
components/src/components/OverflowMenu/OverflowMenuGroup.tsx
components/src/components/SplitButton/SplitButton.spec.tsx
components/src/components/SplitButton/SplitButton.stories.mdx
components/src/components/SplitButton/SplitButton.stories.tsx
components/src/components/SplitButton/SplitButton.tsx
components/src/components/SplitButton/index.ts
components/src/index.ts

`<SplitButton>` er en todelt knapp som skal brukes ved flere relaterte handlinger, der den ene er mest vanlig.
Komponenten består av to knapper: én for den primære handlingen, og én for å åpne en meny med sekundære handlinger.
Når menyen åpnes og en handling velges blir den umiddelbart gjennomført.
Komponenten brukes for å redusere unødvendig kognitiv belastning.
Annet:
- forbedret typings i OverflowMenu.
- fix: `onToggle` var ikke ordentlig støttet i OverflowMenu. La til propen i `<OverflowMenuGroup>`. `onToggle()` kalles ved lukking av menyen.

Ny komponent: SplitButton

---

components/src/components/Grid/Grid.tokens.tsx
components/src/components/Grid/Grid.tsx

Det kan nå settes egen CSS `row-gap` basert på brekkpunkter. Som default er den samme som `column-gap`.

Ny prop `rowGap` i `<Grid>`

---

components/src/components/OverflowMenu/OverflowMenu.tokens.tsx
components/src/components/OverflowMenu/OverflowMenuItem.tsx

Sentrerer ikon med første linje med tekst i OveflowMenu

---

components/src/components/SplitButton/SplitButton.tsx
components/src/types/index.ts
components/src/types/utils.ts

- legger til `ExtractStrict` utility type
- bruker den i `<SplitButton>`

Strengere typings for `purpose` i `<SplitButton>`

---

components/package-lock.json
components/package.json
components/src/components/Select/Select.stories.mdx
components/src/components/Select/Select.tsx

I react-select@5.6.0 støttes `required` som nativ HTML attributt for `<input>`. Legger til støtte i komponenten.
Støtten må testes hos konsumentene som er interesserte.

Støtte for `required` i `<Select>`

---

components/src/components/Search/AutocompleteSearch.context.tsx
components/src/components/Search/Search.spec.tsx
components/src/components/Search/Search.stories.mdx
components/src/components/Search/Search.stories.tsx
components/src/components/Search/Search.tokens.tsx
components/src/components/Search/Search.tsx
components/src/components/Search/SearchAutocompleteWrapper.tsx
components/src/components/Search/SearchSuggestions.tsx
components/src/components/Search/index.ts
components/src/components/Select/Select.tsx
components/src/hooks/useRoveFocus.tsx
components/src/utils/index.tsx
components/src/utils/searchFilter.tsx

- `<SearchAutocompleteWrapper>` - wrapper som håndterer autocomplete
- `<SearchSuggestions>` - liste med forslag
- Fikser initiell state i `useRoveFocus` slik at første elementet i listen får først fokus ved piltasttrykk.

Autocomplete-funksjonalitet med søkeforslag i `<Search>`

---

components/src/components/InlineEdit/InlineEdit.spec.tsx
components/src/components/InlineEdit/InlineEdit.styles.tsx
components/src/components/InlineEdit/InlineEdit.tokens.ts
components/src/components/InlineEdit/InlineEdit.types.tsx
components/src/components/InlineEdit/InlineEditInput.stories.tsx
components/src/components/InlineEdit/InlineEditTextArea.stories.tsx
components/src/components/InlineEdit/InlineInput.tsx
components/src/components/InlineEdit/InlineTextArea.tsx

`hideIcon` tillater å velge om redigerinsikonet skal dukke opp i komponenten. Ikonet vises som default.

Legger til `hideIcon` prop i `<InlineEdit>`

---

components/src/components/ProgressTracker/ProgressTracker.context.tsx
components/src/components/ProgressTracker/ProgressTracker.stories.tsx
components/src/components/ProgressTracker/ProgressTracker.tsx
components/src/components/ProgressTracker/ProgressTrackerItem.tsx

Vi har en rekke komponenter som styrer navigasjon/visning av siden. Disse bør implementeres likt med tanke på oppførsel ved endring av aktivt element. I `<Tabs>` og `<ToggleBar>` styres selve endringen av det aktive elementet internt via wrapperen, og konsumenten kan sette en ekstra callback på wrapper. I `<ProgressTracker>` er det hvert barn som får en `onClick` event satt av konsumenten.
Den forestlåtte løsningen er å gjøre om `<ProgressTracker>` slik at den er lik andre kompontenter.

Konsekvent bruk av `onChange` i komponenter med navigasjon.

---

components/src/components/Grid/Grid.stories.tsx
components/src/components/InlineEdit/InlineEditInput.stories.tsx
components/src/components/InlineEdit/InlineEditTextArea.stories.tsx
components/src/components/Select/Select.stories.mdx
components/src/components/Table/Body.tsx
components/src/components/Table/Foot.tsx
components/src/components/Table/Head.tsx
components/src/components/Table/SortCell.spec.tsx
components/src/components/Table/SortCell.tsx
components/src/components/Table/Table.spec.tsx
components/src/components/Table/Table.stories.mdx
components/src/components/Table/Table.stories.tsx
components/src/components/Table/index.ts
components/src/components/Tooltip/Tooltip.stories.mdx
components/src/components/VisuallyHidden/VisuallyHidden.stories.tsx

Hittil hadde vi komponenter som `<Body>`, `<Row>` osv. for native HTML elementer relaterte til tabell. Disse navnene er ikke beskrivende (`<Row>` kan tolkes som rad i layout osv.). Det er også unødvendig å importere disse komponentene uavhengig av `<Table>`. Derfor gjøres de om til subkomponenter i `<Table>`.
Breaking:
- Endring i importering av konsumenter. Det importeres bare `{ Table }` som inkluderer alle subkomponentene.
- Endring i bruk. For eksempel `<Table.Row>` istedenfor `<Row>`.
- Nye navn for props typer. Alle props typer har nå `Table` som prefiks. For eksempel `TableBodyProps` istedenfor `BodyProps`.
Relatert opprydding:
- Fikser alle stories som bruker tabeller.
- Oppdaterer `<Table>` API og retningslinjer.

Gjør om `<Table>` komponenter til ordentlige subkomponenter

---

components/src/components/Search/Search.tsx

Uten søkeknapp vil søkefeltet bare ha et tomt område på slutten. Det gjør at man aldri får fyllt bredden fullt ut.
Eksempel fra Beramming:
Ønsket oppførsel:

Fikser unødvendig gap i Search

---

components/src/components/Button/Button.styles.tsx
components/src/components/Card/CardAccordion/CardAccordionHeader.tsx
components/src/components/OverflowMenu/OverflowMenuItem.tsx
components/src/components/Table/SortCell.tsx
components/src/components/Tabs/Tab.tsx
components/src/helpers/styling/index.tsx
components/src/helpers/styling/normalize.tsx

Default styling i nettlesere kan føre til uforutsigbar styling i komponenter. Legger til en styling objekt som normaliserer `<button>`.

Legger til style normalizer for knapper

---

components/src/components/Drawer/Drawer.tsx
components/src/components/OverflowMenu/OverflowMenu.tsx
components/src/components/Popover/Popover.tsx
components/src/components/Search/SearchSuggestions.tsx
components/src/components/Select/Select.styles.ts
components/src/components/Tooltip/Tooltip.styles.tsx
components/src/helpers/Backdrop/Backdrop.tsx

Øker z-index til en mer romslig verdi så vi slipper konflikt hos konsumentene som har egne z-index nivåer. Disse komponentene skal som regel vises over alt annet "vanlig" innhold, og bør derfor ha en z-index som distanserer de et stykke fra dem.

Justerer opp z-index

---

components/src/components/Search/Search.tsx
components/src/components/Search/SearchAutocompleteWrapper.tsx

Dersom f.eks. `AutocompletSearch` benyttes vil `context.inputValue` bli satt og skal foretrekkes over `value`. Hvis ikke er `inputValue` `undefined` og konsumenten avgjør om `Search` skal være `controlled / uncontrolled`.

Håndterer input fra Autocomplete til Search

---

components/src/components/Search/SearchSuggestions.tsx
components/src/components/SkipToContent/SkipToContent.tsx
components/src/components/Tooltip/Tooltip.styles.tsx

Følgende `z-index` verdier er satt basert på [z-indeks retningslinjer](https://design.domstol.no/987b33f71/p/4862a7-z-indeks):
- 10 for dekorative ikoner i inputfelt (TextInput, InlineEdit, Search)
- 80 for Tooltip og SearchSuggestions
- 250 for SkipToContent

Oppdaterer `z-index` i enkelte komponenter

---

components/src/hooks/useScreenSize.tsx

Ved innlasting, ble ikke riktig brekkpunt satt, da den kun ble kjørt ved resize. Legger til kall av funksjon, slik at brekkpunkt blir satt korrekt.

ELSA1-195: Sett riktig brekkpunkt ved innlasting for useScreenSize hook

---

components/src/components/FormGenerator/FormGenerator.tsx

Dette gjør at man f.eks. kan sette id og className på parent-elementet i FormGenerator, som er et Grid-element

Legg til støtte for basic HTML props i FormGenerator

---

components/src/components/Grid/Grid.tokens.tsx

`firstHalf` og `secondHalf` blir beregnet ut i fra den totale column count'en for skjermstørrelsen din. For skjermstørrelse XLarge (1920px-bred) var column count for skjermstørrelse XSmall brukt, som førte til at `firstHalf` ville kun bruke de to første kolonnene. Nå bruker `firstHalf` og `secondHalf` 6 kolonner hver.
Merk at vi her har satt en maksbredde i skjemaet, som gjør at det ikke faktisk vokser seg større.

ELSA1-216 Fiks at `firstHalf`/`secondHalf` ikke fungerer på skjermer større enn 1920px

---

components/src/components/FileUploader/fileUploaderReducer.ts
components/src/components/FileUploader/useFileUploader.ts

* Effekten for å sette rootErrors ble i enkelte tilfeller kjørt i loop pga `initialFiles` ble instansiert til `[]` og dermed alltid fikk ny verdi for hver render
* Rydder opp litt slik at vi kun setter `rootErrors` ett sted.

Fikser noen småbugs med FileUploader

---

components/rollup.config.mjs

* Dette fikser feilen som førte til at styled-components ikke ble riktig importert i cjs-bygget av dds-components

Sett interop til 'compat' for cjs-bygg.

---

.github/dependabot.yml

* Tidligere ble dependabot kjørt på components og tokens individuelt, men med nytt workspace setup så kan vi kjøre det på rotnivå og få common-pakker bumpet sammen.

Kjør dependabot for npm på rotnivå

---

.github/workflows/release.yml

kjør bygg før verify for å forsikre oss om at vi har upstream

---

.changeset/mean-dolls-approve.md
packages/components/src/components/Card/Card.stories.tsx
packages/components/src/components/Card/CardAccordion/CardAccordionBody.tsx
packages/components/src/components/Card/CardAccordion/CardAccordionHeader.tsx

Både `CardAccordionHeader` og `CardAccordionBody` tar inn `padding` for å styre størrelsen på innholdet. `CardAccordionHeader` har i tillegg to props for å styre tekststilen.

ELSA1-224 Åpner opp for mer overstyring av CardAccordion

---

.changeset/lucky-books-shake.md
packages/components/src/components/InputMessage/InputMessage.tsx

Tidligere, ved bruk av `<InputMessage />` i en boks:
Etter fiks:

Fjerner bakgrunnsfarge for InputMessage av typen 'tip'

---

.changeset/wise-lies-train.md
apps/testapp/app/routes/card/accordion.tsx
packages/components/src/components/Card/CardAccordion/CardAccordionBody.tsx
packages/components/src/components/Card/CardAccordion/useElementHeight.ts

Oppdaterer høyden på ekspandert `CardAccordion` utifra størrelsen på innholdet.
Andre endringer:
* Lytter på størrelsen via ref med en `ResizeObserver`
* Bruker `height` i stedet for `max-height` i transisjonen
* Fjerner `padding` fra transisjon - ligger implisitt i høyden
* Fjerner `visibility` - har ingen effekt i en transisjon
Har også fjernet `useLayoutEffect` for å se om `ResizeObserver` håndterer problemet i https://github.com/domstolene/designsystem/pull/336. Får ikke verifisert det tilfredsstillende i storybook.

Muliggjør innhold med dynamisk størrelse i CardAccordion

---

.changeset/sharp-drinks-wait.md
packages/formatting/src/dato/formatDato.ts

Dette forenkler bruk av funksjonene i praksis siden den returnerte
typen er snevrere.

Legger til generisk type på datetime-formatering

---

.changeset/config.json
.changeset/sixty-snails-grin.md
packages/components/package.json
packages/page-generator/package.json

Dette gjøres i et forsøk på å gjøre "Update dependencies"-bumper til å ikke bli major-versjon bumper, men er også en endring som uansett er greit å ha på plass.

Sette peer dependency range på interne pakker til å følge major-versjon.

---

.changeset/bright-ears-shout.md
package-lock.json
packages/page-generator/package.json

Dette gjøres for at changesets ikke skal bumpe til ny major for hver endring i dds-components/dds-design-tokens

ELSA1-241 bytte til dependencies istedenfor peerDependencies for dds-pakker i dds-page-generator.

---

packages/components/src/components/ProgressTracker/ProgressTracker.tsx
packages/components/src/components/ProgressTracker/ProgressTrackerItem.tsx

Gir det mening å definere et changeset til denne endringen gitt at forrige changeset ikke ble rullet ut? Jeg tenker at denne går under [forrige PR](https://github.com/domstolene/designsystem/pull/656)

ELSA1-192 "Steg x av y" wrapper på veldig små skjermer

---

.changeset/brave-bugs-wait.md
packages/page-generator/src/components/SectionGenerator.tsx
packages/page-generator/src/helpers/getStandardRow.tsx
packages/page-generator/src/helpers/index.ts
packages/page-generator/src/helpers/isSectionGeneratorRow.tsx
packages/page-generator/src/types/SectionGeneratorProps.tsx
packages/page-generator/src/types/SectionGeneratorRow.tsx
packages/page-generator/src/types/index.ts

Legger til en ny type som brukes i SectionGenerator. Denne støtter property'en "as", som man kan definere som div-element eller fragment.

Legg til ny type SectionGeneratorRow

---

.changeset/rich-buttons-hope.md
packages/components/package.json
packages/development-utils/package.json
packages/formatting/package.json
packages/page-generator/package.json
packages/tokens/package.json

Dette gjør at konsumenter verifiserbart kan sjekke pakkens kilde.
Ref.: https://github.blog/2023-04-19-introducing-npm-package-provenance/

Ta i bruk npm package provenance

---

.changeset/gold-waves-fry.md
packages/components/src/components/Stack/Stack.tsx

Defaultene gjorde at konsumenter fikk kollisjon med egen CSS.

Fjern default verdier for padding og gap i Stack-komponentene

---

.changeset/tame-emus-breathe.md
packages/components/src/components/Button/Button.tsx
packages/components/src/components/Button/Button.types.tsx
packages/components/src/components/Spinner/Spinner.stories.tsx
packages/components/src/components/Spinner/Spinner.tsx

`Spinner` brukes i forskjellige situasjoner der teksten "Innlasting pågår" ikke nødvendigvis passer som beskrivelse. Et eksempel er når `loading` er satt på `Button` ved f.eks. lagring av data. 
Legger til `tooltip`-prop på `Spinner` som kan sette en tooltip-tekst:
For knapper default:
PRen vil beholde samme default som det er i dag.

Legger til valgfri tooltip

---

.changeset/loud-seahorses-yell.md
packages/components/src/components/LocalMessage/LocalMessage.stories.tsx
packages/components/src/components/LocalMessage/LocalMessage.tokens.tsx
packages/components/src/components/LocalMessage/LocalMessage.tsx

Dette gjør at vertikal og horisontal `LocalMessage` har mer konsistent padding.

Gjør padding på LocalMessage mer konsistent på tvers av layouts

---

packages/components/src/components/Select/Select.styles.ts
packages/components/src/components/Select/Select.tokens.tsx

For component size small var multi select 3px større enn andre form elementer, inkludert single select
Endrer på størrelser for å få samsvar på tvers av komponentstørrelser
https://user-images.githubusercontent.com/9928210/236238083-8e2164cf-8a5e-4217-82de-adfa6c43af5e.mov
https://user-images.githubusercontent.com/9928210/236238284-498ff842-79f7-4fb3-9ecb-14769865252c.mov
https://user-images.githubusercontent.com/9928210/236238189-8ab28384-86f9-4f91-b55d-85541ddfae12.mov

Fikser størrelse på Select med isMulti

---

.changeset/heavy-nails-melt.md
packages/components/src/components/DescriptionList/DescriptionList.tokens.tsx
packages/components/src/components/DescriptionList/DescriptionList.tsx
packages/components/src/components/DescriptionList/DescriptionListDesc.tsx

Etter diskusjon med Marianne fjernes overstyring av fontstørrelse for DescriptionList. Appearance styrer dermed kun om teksten i header er bold eller tynn. All tekststørrelse styres av body-fontsize.
Før: 
Etter:

Fjerner overstyring av fontstørrelse for DescriptionList

---

.changeset/khaki-houses-fly.md

Siden React-komponentene er i PascalCase, så burde changeset også referere til de som PascalCase

Endre til PascalCase i changeset for ikoner

---

.changeset/tame-flies-pull.md
packages/components/src/components/Feedback/CommentComponent.tsx
packages/components/src/components/Feedback/Feedback.spec.tsx
packages/components/src/components/Feedback/Feedback.stories.mdx
packages/components/src/components/Feedback/Feedback.stories.tsx
packages/components/src/components/Feedback/Feedback.tsx
packages/components/src/components/Feedback/Feedback.types.tsx
packages/components/src/components/Feedback/FlexContainer.tsx
packages/components/src/components/Feedback/RatingComponent.tsx
packages/components/src/components/Feedback/index.ts
packages/components/src/index.ts

Lager komponent for å gi tilbakemelding:
- Støtter tommel opp/ned
- Støtter, men krever ikke, fritekstfelt i tillegg til tommelrating
- Støtter at den brukes både som kontrollert og ukontrollert komponent
Se video av komponenten in-action:
https://github.com/domstolene/designsystem/assets/37186014/061e8bc7-017d-4abc-8283-cc2bd749887f

ELSA1-188 Lager feedback-komponent

---

packages/components/src/components/Feedback/CommentComponent.tsx
packages/components/src/components/Feedback/Feedback.tsx
packages/components/src/components/Feedback/Feedback.types.tsx
packages/components/src/components/Feedback/RatingComponent.tsx

- Det er nå mulig å sette tittelen som vises når tommel opp/ned er gitt og når "fullstending" feedback (inkl. eventuell kommentar) er gitt, via props
- Når ratingLayout er vertikal, er tommelknappene nå venstrestilt:

ELSA1-188 Småfikser feedback-komponent

---

.changeset/stupid-crabs-eat.md
package-lock.json
packages/core/package.json
packages/form/package.json
packages/icons/package.json
packages/typography/package.json

Ikke helt optimalt, men det kreves for å kunne depende på de av andre pakker i komponentbiblioteket som skal publiseres

Gjør internpakker offentlig.

---

.github/workflows/release.yml
package.json

Når en commit blir pushet til main så lages det en snapshot release. Dette kan være nyttig for å teste ut endringer i pakkene ute i applikasjonene våre, uten å måtte lage en release ut av det.

legge til støtte for snapshot releases

---

.changeset/fluffy-jobs-greet.md
packages/components/src/index.ts

Reverts domstolene/designsystem#900
Problemet var at dds-icons pakken ikke bygde dts

Revert "eksportere typer fra subpakker igjen"

---

.github/workflows/storybook.yml

Denne ble fjernet by mistake. Førte til at deploy feilet, da node/npm ikke var innstallert.

legge inn igjen install action

---

.changeset/twelve-dodos-dance.md
packages/components/src/components/Popover/Popover.stories.tsx
packages/components/src/components/Popover/Popover.tsx

Rearrangerer rekkefølgen på kalkulasjoner, samt dropper en useEffect som krevde rerender for å bli rett.

ELSA1-274 fiks bug hvor første popover åpning scroller til toppen

---

.changeset/empty-windows-kick.md
packages/components/src/components/Select/Select.stories.tsx
packages/components/src/components/Select/Select.tsx
packages/components/src/components/Select/SelectComponents.tsx
packages/components/src/components/Select/index.ts
packages/components/src/components/Select/utils.ts

I 13.10.1 av dds-components gjorde vi typene til Select mer konkrete. Fra `Record<string, unknown>` til `SelectOption<T>`. Dette ble gjort da nyeste versjon av `react-select` ikke var særlig fornøyd med den åpne typen. En konsekvens av dette var at det ikke lenger var typestøtte for å sende inn andre typer enn `SelectOptions` som `options` til Select. For å fikse dette begrenser vi ikke lenger typesignaturen til options, som igjen gir oss mulighet til å sende inn andre verdier enn `SelectOptions` til komponenten, men med litt bedre typesikkerhet for både konsumenter og maintainers av designsystemet.

ELSA1-286 utvidet typestøtte for options i Select

---

.changeset/eight-poems-share.md
packages/components/src/components/date-inputs/DatePicker/DatePicker.mdx
packages/components/src/components/date-inputs/DatePicker/DatePicker.stories.tsx
packages/components/src/components/date-inputs/index.ts
packages/components/src/components/date-inputs/utils/transform.ts

Transformeringsfunksjonene som allerede var der passet ikke lenger til `DatePicker`-en etter at vi fjernet muligheten for at `value` kunne være en generisk `DateValue`.

ELSA1-295 legge til nye transformeringsfunksjoner for DatePicker

---

.changeset/nine-panthers-beg.md
packages/components/src/components/InlineEdit/InlineInput.tsx
packages/components/src/components/InlineEdit/InlineTextArea.tsx
packages/components/src/components/TextArea/TextArea.tsx
packages/components/src/components/TextInput/TextInput.tsx
packages/components/src/components/date-inputs/DatePicker/CalendarPopover.tsx
packages/components/src/components/date-inputs/DatePicker/DateField/DateField.tsx
packages/components/src/components/date-inputs/DatePicker/DatePicker.spec.tsx
packages/components/src/components/date-inputs/DatePicker/DatePicker.tokens.ts
packages/components/src/components/date-inputs/DatePicker/DatePicker.tsx
packages/components/src/components/date-inputs/common/DateInput.tsx
packages/components/src/components/helpers/Input/Input.styles.tsx
packages/components/src/components/helpers/Input/Input.tokens.tsx

`<DatePicker>` var `1px` lavere enn andre input-kilder. Bruker nå mer lik implementasjon som `<TextInput>`, så da burde oppførsel være mer konsistent også.

ELSA1-297 fikse `<DatePicker>` høyde feil

---

.changeset/config.json

Dette dekkes uansett av pnpm, og fører nå bare til at peer-dependencies endres uten at vi ønsker det.

Slå av at changeset oppdatere egne pakker automatisk

---

.changeset/config.json
.github/workflows/pull-request.yml
clean-package.config.json
packages/components/package.json
packages/development-utils/package.json
packages/formatting/package.json
packages/storybook-components/package.json
packages/tokens/clean-package.config.json
packages/tokens/package.json
pnpm-lock.yaml

Ser ut til at clean-package ikke blir kjørt ved release, som fører til at vi publiserer tomme pakker. Beste hadde vært å finne ut av hvorfor dette ikke skjer, men i og med at vi ikke lenger har like stort behov for clean-package, siden vi ikke lenger skal ha mange pakker, så tenker jeg det er best å bare fjerne den istedet.

Fjerne bruk av clean-package

---

.changeset/friendly-scissors-smile.md
packages/components/src/components/helpers/Input/Input.styles.tsx

Regelen som ble brukt for DatePicker kan ikke brukes for input/textarea.

ELSA1-306 fikse at input/textarea i disabled/readonly hadde hover-effekt

---

.changeset/smooth-wombats-live.md
packages/components/src/components/helpers/Input/Input.styles.tsx

ELSA1-306 fjerner fokus på read-only

---

.changeset/shaggy-peas-lie.md
packages/components/src/components/LocalMessage/LocalMessage.tokens.tsx
packages/components/src/components/LocalMessage/LocalMessage.tsx

Fjerner `defaultWidth` da komponenten ikke skal ha hardkodet bredde, og legger på padding for bedre avstand.

ELSA1-230 fjerner `defaultWidth` på `LocalMessage`

---

.changeset/quiet-apes-lay.md
packages/components/src/components/SelectionControl/Checkbox/Checkbox.tsx
packages/components/src/components/SelectionControl/Checkbox/CheckboxGroup.tsx
packages/components/src/components/SelectionControl/Checkbox/CheckboxGroupContext.tsx
packages/components/src/components/SelectionControl/RadioButton/RadioButton.tsx
packages/components/src/components/SelectionControl/RadioButton/RadioButtonGroup.tsx
packages/components/src/components/SelectionControl/RadioButton/RadioButtonGroupContext.tsx
packages/components/src/components/SelectionControl/SelectionControl.styles.tsx
packages/components/src/components/SelectionControl/SelectionControl.utils.tsx

Standariserer styling av `readOnly` og `disabled` tilstander. Legger til støtte for disse tilstandene i `CheckboxGroup`.

Fikser `readOnly` og `disabled` i `RadioButtonGroup` og `CheckboxGroup`.

---

.changeset/violet-moons-allow.md
packages/components/src/components/EmptyContent/EmptyContent.mdx
packages/components/src/components/EmptyContent/EmptyContent.tsx

- `EmptyContent` har alltid tittel i `<h5>`; Det er vanlig at tittel for tom tilstand er en overskrift, men det er viktig at den følger hierarkiet på siden. Konsumenter skal kunne velge nivå selv.
- Opprydding av docs story.
- Beskrivelser av attributter for docs.

Støtte for `headingLevel` i `EmptyContent`.

---

.changeset/mighty-panthers-talk.md
packages/components/src/components/ToggleBar/ToggleRadio.tsx

Fikser manglende støtte for `aria-label` og `aria-labelledby`.

ELSA1-325 Fikser støtte for ARIA i `<ToggleRadio />`

---

.changeset/cyan-kiwis-glow.md
packages/components/src/components/FavStar/FavStar.tsx

Trykkeflaten er 25% mindre grunnet bruken av `transform: scale(0.75)`. Flytter denne regelen til selve ikonet, slik at hele komponenten ikke blir mindre.
Fikser også animasjon på ikonet, slik at bakgrunnsfargen blir gradvis synlig.

ELSA1-320 Fikser trykkeflate i `<FavStar />`

---

.changeset/heavy-experts-agree.md
packages/components/src/components/OverflowMenu/OverflowMenu.tsx
packages/components/src/components/OverflowMenu/OverflowMenuItem.tsx
packages/components/src/components/Search/SearchSuggestions.tsx
packages/components/src/components/Tabs/Tab.tsx
packages/components/src/components/Tabs/TabList.tsx
packages/components/src/components/Tabs/Tabs.stories.tsx
packages/components/src/hooks/useRoveFocus.tsx

Trenger ikke å gjøre noe med keydown events når hooken ikke aktivt styrer fokus.
Syntes det var litt forvirrende med den `reset`-proppen, så endret den samtidig til å heller være en "aktiv toggle". Føler det gir mer mening 😅

ELSA1-323 fikse at `useRoveFocus` stjeler keydown mens inaktiv

---

.storybook/preview-head.html
.storybook/preview.tsx
packages/components/src/components/BackLink/BackLink.stories.tsx
packages/components/src/components/Breadcrumbs/Breadcrumb.stories.tsx
packages/components/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
packages/components/src/components/SelectionControl/Checkbox/CheckboxGroup.stories.tsx

Styling var defaulten til Storybook; wrapper alt i `<Unstyled />` og oppdaterer enkelte stiler i `preview-head.html`.

Fikser styling i Storybook docs

---

.changeset/fluffy-chefs-invent.md
packages/components/src/components/FileUploader/FileUploader.tsx
packages/components/src/components/FileUploader/index.ts
packages/components/src/components/FileUploader/types.ts
packages/components/src/components/FileUploader/useFileUploader.ts

Eksporterer følgene types fra `<FileUploader />`: `FileUploaderAccept`, `FileList` og `FileUploaderProps` slik at konsumenter kan importere de i sine løsninger.

ELSA1-332 Eksporterer types fra `<FileUploader />`

---

.changeset/kind-mangos-roll.md
packages/components/src/components/date-inputs/DatePicker/DatePicker.tsx
packages/components/src/components/date-inputs/TimePicker/TimePicker.stories.tsx
packages/components/src/components/date-inputs/TimePicker/TimePicker.tsx

Fjerner `disabled` prop, da det er `isDisabled` som er støttet.

Fjerner `disabled` prop i `<TimePicker />`

---

.changeset/fast-bags-boil.md
packages/components/src/components/InternalHeader/InternalHeader.stories.tsx
packages/components/src/components/InternalHeader/InternalHeader.styles.tsx
packages/components/src/components/InternalHeader/InternalHeader.tsx
packages/components/src/components/InternalHeader/InternalHeader.types.tsx
packages/components/src/components/helpers/styling/index.ts
packages/components/src/components/helpers/styling/inheritLinkStyling.tsx

Støtte for prop `applicationNameHref` som gjør appnavnet til en lenke til hjemmesiden i `<InternalHeader />`.

ELSA1-339 Lenke til hjem i `<InternalHeader />`

---

.changeset/seven-pants-hunt.md
packages/components/src/components/date-inputs/DatePicker/Calendar/Calendar.tsx
packages/components/src/components/date-inputs/DatePicker/Calendar/CalendarCell.tsx
packages/components/src/components/date-inputs/DatePicker/CalendarPopover.tsx

Knappene til å bla i måneder kunne ikke brukes, kalender-popover ble lukket istedet.
Gjorde det slik at popover lukkes kun hvis brukeren: velger en dag, klikker utenfor, trykker Esc, klikker Tab fra en dag eller Shift-Tab på første knappen.

ELSA1-340 Fikser <Datepicker /> i Safari 

---

.changeset/tall-sheep-exercise.md
packages/components/package.json
packages/components/src/components/FileUploader/FileUploader.spec.tsx
packages/components/src/components/FileUploader/FileUploader.tsx
packages/components/src/components/FileUploader/attr-accept.ts
packages/components/src/components/FileUploader/utils.ts
pnpm-lock.yaml

`attr-accept` har problemer med ESM output. Siden pakken uansett er så liten, og den ikke har blitt oppdatert på 4 år, så er det like greit å bare "inline" implementasjonen.

ELSA1-338 fikse at `accept`-prop i `<FileUploader>` kaster feil ved opplasting

---

.changeset/stale-hats-beam.md
packages/components/src/components/Typography/Heading/Heading.mdx
packages/components/src/components/Typography/Heading/Heading.stories.tsx
packages/components/src/components/Typography/Heading/Heading.tsx

- Automatisk skalering av stiler `headingSans08-04`. På skjerm under 600px skal komponenten automatisk bruke typografistil et steg mindre.
- Eksempel: hvis `headingSans08` er valgt skal den automatisk bli `headingSans07` på mindre skjerm.

ELSA1-13 Skalering av overskrifter på mobil

---

.changeset/good-mirrors-reflect.md
packages/components/package.json
packages/components/src/components/date-inputs/DatePicker/Calendar/Calendar.tsx
packages/components/src/components/date-inputs/DatePicker/Calendar/CalendarGrid.tsx
packages/components/src/components/date-inputs/DatePicker/DateField/DateField.tsx
packages/components/src/components/date-inputs/DatePicker/DatePicker.tsx
pnpm-lock.yaml

`useCalendar` tar ikke inn `locale`, så vi må bruke `I18nProvider` for å sette språk istedet.
Det er nok uansett bedre å bruke `I18nProvider` til dette, da det kan bli litt enklere i fremtiden om vi ønsker å la konsumenter overstyre locale.

ELSA1-341 fikse at Calendar brukte språket til nettleser for måned

---

.changeset/lazy-spiders-lie.md
packages/components/src/components/Table/normal/Cell.tsx

`layout`-prop legger til en flex `<div>` i en celle for  å styre layout; det er som regel unødvendig.
Fjerner div-en for alle varianter av layout unntatt tekst og ikon. Bruker `text-align` direkte på cellen i de andre variantene.

ELSA1-296 Fjerner `<div>` fra `<Table.Cell />`

---

.changeset/great-humans-approve.md
packages/components/src/components/Grid/Grid.tsx

Dette gjøres for at PageGenerator kan få samme styling når Fieldset-komponenten er i bruk.

fix: Eksporter styling for Grid

---

.changeset/wicked-queens-ring.md
packages/components/tsup.config.ts

Gjør det enklere å bruke komponentene i Next.js. Dette gjør at vi kan bruke Elsa-komponenter i server components.

ELSA1-313 marker alle komponenter som client components

---

.changeset/lazy-ties-move.md
packages/components/src/components/OverflowMenu/OverflowMenu.tsx
packages/components/src/components/Search/Search.stories.tsx
packages/components/src/components/Tabs/TabList.tsx

Fjerner unødvendig `aria-label` fra enkelte komponenter: Tabs, OverflowMenu. Den informerte om retning for fokus, noe som er implisitt formidlet via rolle.

ELSA1-362 Fjerner unødvendig `aria-label`

---

.changeset/olive-bugs-beg.md
packages/components/src/components/SelectionControl/Checkbox/CheckboxGroup.stories.tsx
packages/components/src/components/SelectionControl/RadioButton/RadioButtonGroup.stories.tsx
packages/components/src/components/SelectionControl/SelectionControl.styles.tsx

Endrer fokusmarkering i `<Checkbox />` og `<RadioButton />` til å markere kun inputelementet, ikke ledetekst. Fokusmarkeringen settes ikke ved museklikk, kun tastaturfokus.

ELSA1-364 Fokusmarkering i selection cotrols

---

.changeset/heavy-zoos-deliver.md
packages/components/src/components/Feedback/CommentComponent.tsx
packages/components/src/components/Feedback/Feedback.stories.tsx
packages/components/src/components/Feedback/Feedback.tsx
packages/components/src/components/Feedback/Feedback.types.tsx

I overbygg begynner vi nå å legge inn oversettelser og da er det nyttig å kunne endre teksten på tipen til `<TextArea>`-et i `<Feedback>`-komponenten.

legge til `textAreaTip`-prop

---

.changeset/violet-boats-serve.md
packages/components/package.json
packages/storybook-components/package.json
pnpm-lock.yaml

Fjerner styled-components fra pakkene som ikke bruker de lenger: dds-components og storybook-components. Fjerner også focus-visible da den ikke trengs.

ELSA1-385 Fjerner styled-components

---

.changeset/new-hats-fly.md
.changeset/odd-countries-suffer.md
packages/components/src/components/Button/Button.module.css
packages/components/src/components/Chip/Chip.tsx
packages/components/src/components/EmptyContent/EmptyContent.tsx
packages/components/src/components/Feedback/Feedback.module.css
packages/components/src/components/Feedback/RatingComponent.tsx
packages/components/src/components/LocalMessage/LocalMessage.tsx
packages/components/src/components/Pagination/Pagination.tsx
packages/components/src/components/Popover/Popover.tsx
packages/components/src/components/Select/Select.module.css
packages/components/src/components/SelectionControl/SelectionControl.module.css
packages/components/src/components/TextInput/TextInput.module.css
packages/components/src/components/Tooltip/Tooltip.module.css
packages/components/src/components/Tooltip/Tooltip.tsx
packages/components/src/components/date-inputs/DatePicker/DateField/CalendarButton.tsx
packages/components/src/components/date-inputs/TimePicker/TimePicker.tsx
packages/components/src/components/date-inputs/common/DateInput.module.css
packages/components/src/utils/icon.ts

Mindre styling fixes på ting som ble litt feil under CSS-migreringen:
- Spacing mellom icon og text i Small `<Button size="small">` skal være `0_25`, ikke `0_5`
- `<EmptyContent>`: `<h2>` for tittel som default med `typographyType="headingSans02"`.
- `<Feedback>`: ikke bruke `<Button>`, den passer ikke i denne konteksten; gi ikonet action-hover farge på på hover.
- `<LocalMessage>`: bruke riktig fargetokens for ikonet
- Bruke subtle border i `<Popover>`
- Fjerne hover på selected i `<RadioButton>`
- Bruke medium ikon i small-varianten av skjemakomponenter som kan ha et ikon.
- Bruke subtle border i `<Tooltip>`
- Paginering: <Select> skal ha samme størrelse som knapper

ELSA1-392 Style fixes

---

packages/components/src/components/Select/Select.mdx

Oppdaterer `<Select>` docs til å mer info om problemstillingen rundt `menuPortalTarget` som krangler med Lovisa Core.
Oppdaterer også docs om `getOptionValue` og `getOptionLabel`, og legger til noen eksempler.

ELSA1-389 `menuPortalTarget` i `<Select>` docs

---

.changeset/stupid-impalas-wave.md
README.md
packages/development-utils/src/EnvironmentBannerProvider/EnvironmentBanner.tsx

For prototyper som ikke har test-data ønsker man å ha et PROTOTYPE enviornment som er lilla.
refs: https://domstol.atlassian.net/browse/OBYGG-112

OBYGG-112 - Eget PROTOTYPE env for banner

---

packages/components/src/components/Card/CardAccordion/CardAccordionHeader.tsx
packages/components/src/components/Icon/Icon.tsx
packages/components/src/components/Spinner/Spinner.tsx
packages/components/src/utils/color.tsx

svg kan ikke ta CSS variabel som width eller height-atributt, må være en streng. Bytter til ddsTokens i JS i relevante komponenter.

Fikser svg sizing bug

---

.changeset/cold-cooks-wonder.md
packages/components/src/components/TextArea/TextArea.module.css
packages/components/src/components/TextArea/TextArea.tsx
packages/components/src/components/TextInput/TextInput.module.css
packages/components/src/components/TextInput/TextInput.tsx
packages/components/src/components/date-inputs/common/DateInput.module.css
packages/components/src/components/date-inputs/common/DateInput.tsx
packages/components/src/components/helpers/Input/Input.module.css

`width`-prop i `<TextInput>`, `<TextArea>`, `<TimePicker>` og `<DatePicker>` påvirker nå kun selve inputfeltet. Det betyr at hele komponenten tar den bredden den får tilgjengelig. Ledetekst, feilmeding og hjelpetekst kan bli bredere enn inputfeltet.

ELSA1-376 `width`-prop påvirker selve inputfeltet

---

.changeset/dull-olives-visit.md
packages/components/src/components/TextArea/TextArea.module.css
packages/components/src/components/TextArea/TextArea.stories.tsx
packages/components/src/components/TextArea/TextArea.tsx
packages/components/src/components/TextInput/TextInput.module.css
packages/components/src/components/TextInput/TextInput.tsx
packages/components/src/components/helpers/Input/CharCounter.tsx
packages/components/src/components/helpers/Input/Input.module.css
packages/components/src/components/helpers/Input/index.ts

Viser tegnteller ved `maxLength`, som i `<TextInput>`.
Flytter `<CharCounter>` til helpers og refaktorerer `<TextArea>` i samme slengen.

ELSA1-401 Støtte for tegnteller i `<TextArea>`

---

.changeset/green-schools-lie.md
packages/components/src/components/TextInput/TextInput.module.css
packages/components/src/components/TextInput/TextInput.tsx

Fikser bug som satt feil bredde i `<TextInput>` ved bruk av ikon og suffiks.
Før:
Etter:

ELSA1-403 Bug bredde i `<TextInput>`

---

packages/app-shell/package.json

Fikser dds-components peerDependency i app-shell slik at den ikke trenger å bumpe versjon.

peerDependency bump fix

---

.changeset/few-zoos-turn.md
packages/components/src/components/Search/Search.module.css

Fikser spacing i `<Search>` og at den tar 100% bredde.
Fikser denne med spacing:

ELSA1-404 Fikser spacing i `<Search>`

---

.changeset/tough-readers-repeat.md
packages/components/src/components/EmptyContent/EmptyContent.mdx
packages/components/src/components/EmptyContent/EmptyContent.spec.tsx
packages/components/src/components/EmptyContent/EmptyContent.stories.tsx
packages/components/src/components/EmptyContent/EmptyContent.tsx
packages/storybook-components/src/StorybookLinkRow.tsx

Utvider typen til `message` i `EmptyContent` til `ReactNode`, slik at den kan støtte variert innhold og ikke kun `string`.

ELSA1-411 Utvider `message` type i `EmptyContent`

---

.storybook/main.ts
package.json

Alle storybook-pakker har spesifikk versjon i `package.json`, mens addon-links hadde med `^`; dle ble feil versjon på den. Fjerner caret.
Fjerner også story path som ikke eksisterer.

Fikser feil versjon av `@storybook/addon-links`

---

.changeset/silly-swans-clap.md
packages/components/src/components/Card/Card.module.css

Setter `display: block;` i CSS for `<Card cardType="navigation">`, da den returnerer `<a>` og er i utganspunktet et inline-element.
Før:
Etter:

ELSA1-417 Fikser visuell bug i navigation Card

---

.changeset/giant-plums-search.md
packages/components/src/components/Drawer/Drawer.tsx
packages/components/src/components/LocalMessage/LocalMessage.stories.tsx
packages/components/src/components/Modal/Modal.tsx
packages/components/src/components/Popover/Popover.tsx
packages/components/src/components/SkipToContent/SkipToContent.stories.tsx

Default tittel/header i `<Drawer>`, `<Modal>` og `<Popover>` returnerer nå `<h2>`, slik at overskriftshierarkiet opprettholdes uansett kontekst. På denne måten unngår vi problemer rundt universell utforming.

ELSA1-418 `<h2>`som header i flate-komponenter

---

.changeset/khaki-spiders-agree.md
packages/components/src/components/Breadcrumbs/Breadcrumbs.mdx
packages/components/src/components/Breadcrumbs/Breadcrumbs.module.css
packages/components/src/components/Breadcrumbs/Breadcrumbs.spec.tsx
packages/components/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
packages/components/src/components/Breadcrumbs/Breadcrumbs.tsx
packages/components/src/components/Grid/Grid.stories.tsx
packages/components/src/components/InternalHeader/InternalHeader.mdx
packages/components/src/components/InternalHeader/InternalHeader.module.css
packages/components/src/components/InternalHeader/InternalHeader.spec.tsx
packages/components/src/components/InternalHeader/InternalHeader.stories.tsx
packages/components/src/components/InternalHeader/InternalHeader.tsx
packages/components/src/components/InternalHeader/InternalHeader.types.tsx
packages/components/src/components/Pagination/Pagination.mdx
packages/components/src/components/Pagination/Pagination.module.css
packages/components/src/components/Pagination/Pagination.spec.tsx
packages/components/src/components/Pagination/Pagination.stories.tsx
packages/components/src/components/Pagination/Pagination.tsx

Prop `smallScreen` i komponentene `<Breadcrumbs>`, `<InternalHeader>` og `<Pagination>` gjøres om til `smalScreenBreakpoint`; den tar inn navn på et brekkpunkt og gjør komponenten responsiv, slik at versjonen for liten skjerm vises ved oppgitte brekkpunket og nedover vha kun CSS.

ELSA1-423 `smallScreenBreakpoint` prop

---

.changeset/five-garlics-taste.md
packages/app-shell/src/AppShell/AppShell.tsx
packages/components/src/components/Grid/Grid.stories.tsx
packages/components/src/components/InternalHeader/InternalHeader.mdx
packages/components/src/components/InternalHeader/InternalHeader.spec.tsx
packages/components/src/components/InternalHeader/InternalHeader.stories.tsx
packages/components/src/components/InternalHeader/InternalHeader.tsx
packages/components/src/components/InternalHeader/InternalHeader.types.tsx
packages/components/src/components/InternalHeader/NavigationItem.tsx
packages/components/src/components/OverflowMenu/OverflowMenu.spec.tsx
packages/components/src/components/OverflowMenu/OverflowMenu.types.tsx

Endrer navn på props i `<InternalHeader>`: `userProps` til `user`, `navigationElements` til `navItems` og `contextMenuElements` til `contextMenuItems`. Dette standardiserer navngiginv på tvers av komponenter.
I tillegg endrer vi de samme props; de tar inn `children` istedenfor `title` eller `name` for å vise tekst i elementer i menyen og lenker.
På denne måten følger props samme standard som andre komponenter.

ELSA1-437 Standardisering i `<InternalHeader>`

---

.changeset/khaki-mails-visit.md
packages/components/src/components/Table/normal/Table.module.css

Fikser bakgrunnsfarge i rader i `<Table density="extraCompact">`, slik at oddetall rader har farge.
Før:
Etter:

ELSA1-433 Styling i `<Table density="extraCompact">`

---

.changeset/two-mayflies-perform.md
packages/components/src/components/Search/Search.mdx
packages/components/src/components/Search/Search.types.tsx

Nå kan `buttonProps`-prop også ta inn `icon` og `loadingTooltip`.

ELSA1-438 Utvider type for `buttonProps` i `<Search>`

---

.changeset/mean-fans-boil.md
.changeset/orange-poems-hunt.md
packages/components/src/components/Search/Search.module.css
packages/components/src/components/Search/Search.tsx
packages/components/src/components/Select/Select.module.css
packages/components/src/components/Select/Select.styles.ts
packages/components/src/components/Select/Select.tsx
packages/components/src/components/Select/SelectComponents.tsx
packages/components/src/components/TextInput/TextInput.module.css
packages/components/src/components/TextInput/TextInput.tsx
packages/components/src/components/helpers/Input/Input.module.css

Høyden var feil pga store ikoner og bruk av kun padding/margin for å posisjonere custom ikon.
- Gjør indikator-ikonene mindre per Figma-skisser
- Standardiserer ikonplassering på tvers av input-komponenter via absolutt posisjonering, slik at den ikke påvirker høyden på komponenten.

ELSA1-440 Fikser høyde i `<Select componentSize="small">`

---

.changeset/proud-buses-swim.md
packages/components/src/components/Popover/Popover.tsx

Fikser bug som gjorde at `<Popover>` ikke fikk klassenavn satt via `className` prop. `className` ble duplisert og satt kun CSS klasser fra Elsa, slår de sammen.

ELSA1-442 Fikser `<Popover>` `className` bug

---

.changeset/silly-doors-retire.md
packages/components/README.md
packages/components/src/components/DetailList/DetailList.mdx
packages/components/src/components/DetailList/DetailList.module.css
packages/components/src/components/DetailList/DetailList.stories.tsx
packages/components/src/components/DetailList/DetailList.tsx
packages/components/src/components/DetailList/DetailListDesc.tsx
packages/components/src/components/DetailList/DetailListRow.tsx
packages/components/src/components/DetailList/DetailListTerm.tsx
packages/components/src/components/DetailList/index.ts
packages/components/src/components/Table/normal/Table.types.ts
packages/components/src/index.ts
packages/components/src/types/Density.tsx
packages/components/src/types/index.ts

`<DetailList>` er en beskrivelsesliste formatert som en tabell. Den har tilhørende subkomponenter, od til sammen returnerer de beskrivelsesliste (`<dl>`, `<dt>` og `<dl>`) og en `<div>` for å formatere en rad. Komponenten brukes til å vise informasjon på en ryddig måte:
- bygges med div-rader i en beskrivelsesliste
- den første cellen i raden er et uttrykk eller ledetekst (term)
- resterende celler i raden innheholder detaljer om dette utrykket, eller erelevante lenker og knapper.

ELSA1-409 Ny komponent: `<DetailList>`

---

.changeset/weak-pianos-yawn.md
packages/components/src/components/BackLink/BackLink.module.css
packages/components/src/components/BackLink/BackLink.tsx

`text-decoration-color: transparent;` funker ikke i `<BackLink>` eller `<InlineButton>` ved `:hover` i Safari.
Endrer litt styling i `<BackLink>` for å få det til å funke, samt standardisere styling i lenker.
`<InlineButton>` er vanskelig å fikse uten "hacking" eller ofring av animasjon på tvers av nettlesere. I tilleg kom støtte for regelen i Safari ganske nylig. Siden feilen er så liten venter vi og ser om det det blir fikset.

ELSA1-399 Fikser underline bug i Safari

---

.changeset/slow-eggs-wonder.md
packages/components/src/components/ProgressTracker/ProgressTrackerItem.tsx

Fikser bug der `onClick` i `ProgressTrackerItem` ikke var valgfri.

ELSA1-448 Gjør `onClick` valgrfri i `ProgressTrackerItem`

---

.changeset/eleven-emus-study.md
packages/components/src/components/SplitButton/SplitButton.tsx

Manglende key ga feil i konsollet i nettleseren.

fix(splitbutton): Sett unik key på SecondaryActions i SplitButton

---

.changeset/brave-turkeys-raise.md
packages/components/src/components/Typography/Typography/Typography.tsx
packages/components/src/components/Typography/Typography/Typography.utils.ts
packages/components/src/components/Typography/typographyStyles.module.css

Fikser bug der `<Caption withMargins="true">` la seg inni tabellen istedenfor over.
Før: 
Etter:

ELSA1-449 Fikser Caption layout bug

---

.changeset/rude-parrots-complain.md
packages/components/src/components/ButtonGroup/ButtonGroup.module.css

I `<ButtonGroup>` vil barn ha dobbel border, det er ønsket med enkel border. Slik det er løst idag: `<ButtonGroup>` setter fargen på den ene i doble border til `transparent`; når knappen er trykt inn og border skal vises igjen settes fargen til `initial`. Denne fargen er default fra nettleseren og er feil, noe som ikke synes veldig godt når border er mørkegrå. Dette vil synes veldig godt med andre farger hvis det blir endringer.
Dette løses med negativ margin.
Før (border med feil farge markert):
Etter:

ELSA1-452 Fikser border farge i ButtonGroup

---

packages/components/src/components/SplitButton/SplitButton.stories.tsx

Fikser bug der `loading`-variant gjorde knappen større. Størrelsen følger original innhold før `loading` slår inn. La til `children` for å ha størrelse å følge.
Så slik ut:

ELSA1-454 Fikser visuell bug i SplitButton story

---

.changeset/clever-actors-clap.md
packages/components/src/components/date-inputs/common/DateInput.module.css

I Lovisa kan kalender-popover legge seg over input-feltet og ikke under. Når brukerer blar i måneder og kommer til en med forskjellig antall uker, vil popover "hoppe". Da må brukeren flytte på musa for å fortsette å bla. 
https://github.com/user-attachments/assets/eac67bb4-da82-45b9-935a-dcf9c5d138a8
Setter fast høyde på kalender-popover i `<DatePicker>`. På denne måten har den forutsigbar størrelse, og ingenting hopper ikke når antall uker i måneden forandrer seg.

ELSA1-453 Fikser hopping av kalender i `<DatePicker>`

---

packages/components/package.json

Får warning at `types` condition i `packages/components/package.json` ikke blir brukt da den kommer etter `import` og `require`:
Flytter types til toppen.

ELSA1-462 Flytter `types` lengre opp i exports

---

.changeset/giant-lemons-chew.md
packages/components/src/components/ToggleButton/ToggleButton.module.css
packages/components/src/components/ToggleButton/ToggleButton.tsx

Fikser spacing mellom ikon og tekst samt foran ikon.
Før:
Etter:

ELSA1-469 Fikser spacing i `<ToggleButton>`

---

.changeset/hip-pigs-design.md
packages/components/src/components/Skeleton/Skeleton.tsx

Fikser bug der `border-radius` prop var påkrevd i `<Skeleton>`.

ELSA1-475 `border-radius` bug i `<Skeleton>`

---

.changeset/gentle-zoos-chew.md
packages/components/src/components/Card/CardAccordion/CardAccordion.module.css
packages/components/src/components/Card/CardAccordion/CardAccordion.tsx
packages/components/src/components/helpers/AccordionBase/AccordionBase.module.css

Fikser `border-radius` i `<Card cardType="expandable">` ved hover.
Før:
Etter:
Uten hover:

ELSA1-473 `border-radius` bug i `<Card>`

---

.changeset/brave-humans-run.md
packages/app-shell/package.json
packages/components/package.json
packages/development-utils/package.json
packages/storybook-components/package.json
pnpm-lock.yaml

fjerner samtidig ubrukte deps/peerDeps på react-dom i diverse pakker.
Ser ikke ut til at noen av de brekkende endringene som ligger i RC treffer oss, så da er det greit å bare tillate bruk av React 19 sammen med designsystemet. Kjørte også React 19 RC sin codemod, og den endret heller ingenting.
Vi ønsker å oppgradere til Next.js 15, og de bruker React 19 RC, og fikk under oppgradering da litt kjeft av npm for å overskride denne dependency rangen 😅

legge til støtte for react 19

---

.changeset/fast-needles-exist.md
packages/components/src/components/Select/NativeSelect/NativeSelect.module.css

Det ble originalt satt custom styling på høyde pga noen små forskjeller mellom komponenter, men den ser ut til å fungere dårligere. Fjerner den stylinga.

ELSA1-496 Fikser høyde i `<NativeSelect>`

---

.changeset/fresh-windows-join.md
packages/components/src/components/Select/Select.module.css
packages/components/src/components/Select/Select.tsx
packages/components/src/components/TextInput/TextInput.module.css

Setter default bredde på minste varianten av `<Select>` til å følge `<TextInput>`.
Fjenrner ubrukt styling i samme slengen.

ELSA1-497 Fikser default bredde i `<Select>`

---

.changeset/polite-yaks-return.md
packages/components/src/components/Drawer/Drawer.module.css
packages/components/src/components/helpers/Paper/Paper.module.css

Setter `border-radius` i `<Drawer>` til 0, da flata tar hele viewport-høyden.
Bruker `:where()` i styling i `<Paper>` for enkel override.

ELSA1-492 Fikser `border-radius` i `<Drawer>`

---

.changeset/thirty-adults-watch.md
packages/components/src/components/Accordion/Accordion.module.css
packages/components/src/components/Accordion/AccordionHeader.tsx
packages/components/src/components/Card/CardAccordion/CardAccordion.module.css
packages/components/src/components/Card/CardAccordion/CardAccordionHeader.tsx
packages/components/src/components/helpers/AccordionBase/AccordionBase.module.css

Flytter chevron i `<AccordionHeader>` til venstre for teksten. Dette sørger for at brukeren forstår at hele headeren er klikkbar, samt vet hva tilstanden på komponenten er ved zoom og o.l.
Før:
Etter:

ELSA1-489 Flytter chevron i `<AccordionHeader>`

---

.changeset/thirty-birds-march.md
packages/components/src/components/SelectionControl/Checkbox/Checkbox.mdx
packages/components/src/components/SelectionControl/Checkbox/CheckboxGroup.stories.tsx
packages/components/src/components/SelectionControl/Checkbox/CheckboxGroup.tsx

Egen story i `CheckboxGroup.stories.tsx`. Fkser også at hvis prop `label` ikke settes i `<CheckboxGroup>`, blir dens `<span>` ikke rendret.

Eksempel på bruk av `<CheckboxGroup>` med `<Fieldset>`

---

.changeset/angry-kiwis-hear.md
packages/components/src/components/date-inputs/DatePicker/Calendar/CalendarGrid.tsx
packages/components/src/components/date-inputs/DatePicker/CalendarPopover.tsx
packages/components/src/components/date-inputs/DatePicker/DatePicker.stories.tsx
packages/components/src/components/date-inputs/DatePicker/DatePicker.tsx

Den styrer visning av ukenumre. `true` som default.
Med:
Uten:

ELSA1-470 Støtte for `showWeekNumbers` prop i `<DatePicker>`

---

.changeset/shiny-cars-brush.md
packages/dds-components/src/components/Button/Button.module.css
packages/dds-components/src/components/SplitButton/SplitButton.module.css

Ved `:active` state blir border på den ene siden gjennomsiktig. For å unngå det fikses komponenten som `<ButtonGroup>`, med negativ `margin`.
Før:
Etter:

ELSA1-504 Fikser border i `<SplitButton>`

---

.changeset/serious-years-drive.md
packages/dds-components/src/components/Feedback/RatingComponent.tsx
packages/dds-components/src/components/ToggleBar/ToggleBar.tsx

Fikset bug der `<ToggleBar>` og `<Feedback>` rendret `<label>` for tekster som ikke er semantiske ledetekster. `<ToggleBar>` returnerer nå `<span>`, slik det at følger mønsteret fra andra selection control-komponenter. `<Feedback>` returnerer `<h2>` med label styling, da den relevante teksten blir overskriften for  feedback-seksjonen hos konsumenten.

ELSA1-508 Fjerner `<label>` i noen komponenter

---

.github/dependabot.yml

Legge til egen gruppe i YAML, da Typescript ikke følger semver og update blir lettere å håndtere i enestående PR.

ELSA1-512 Gruppe for typescript i dependabot YAML

---

packages/dds-components/src/components/ProgressTracker/ProgressTracker.stories.tsx

Eksempler som bruker `<Drawer>` resulterte i Error da de må wrappes inn `<StoryThemeProvider>` for å få ref til `<div>` `<Drawer>` rendres i. Wrapper relevante stories.
Før:
Etter:

ELSA1-514 Legger ProgressTracker stories i ThemeProvider

---

packages/dds-components/src/components/ThemeProvider/ThemeProvider.tsx

Endre DdsTheme  fra `'core' | 'public'` til `keyof typeof ddsTokens` da `ddsTokens` er delt opp i tema basert på nanv. Det blir mer gjenbrukbart, samt lettere å verifisere om type-feil kommer fra dds-design-tokens eller dds-components.

ELSA1-516 Endrer `type DdsTheme` til `keyof typeof`

---

packages/dds-components/src/components/Pagination/Pagination.stories.tsx
packages/dds-components/src/components/date-inputs/DatePicker/DatePicker.stories.tsx

Eksempler som bruker `<Modal>` og `<Select>` resulterte i Error da de må wrappes inni `<StoryThemeProvider>` for å få ref til `<div>` disse komponentene rendres i. Wrapper relevante stories.
Før:
Etter:

ELSA1-518 Fikser ThemeProvider-errors i stories

---

packages/dds-components/src/components/Table/normal/Table.mdx
packages/dds-components/src/components/Table/normal/Table.stories.tsx

Sidemenyen for Table er rotete, endrer litt på strukturen.
Før:
Etter:

Fikser Storybook sidemeny for Table

---

.changeset/smart-news-sparkle.md
packages/app-shell/package.json
pnpm-lock.yaml

Endrer devPependencies til Elsa slik at de peker til nåværende major, slik at pakken ikke må oppdateres med endringer framover.

ELSA1-527 Gjør AppShell deprecated

---

.changeset/empty-kangaroos-hang.md
packages/dds-components/src/components/Table/collapsible/CollapsibleTable.stories.tsx
packages/dds-components/src/components/Table/normal/Table.stories.tsx
packages/dds-components/src/components/Table/normal/TableWrapper.tsx

Fjerner referanser til `window.innerWidth` i `useState` og `handleResize`. Erstatter de med ref til `<div>` returnert av `<ThemeProvider>` og `clientWidth`.
Ser ikke ut til å fungere noe særlig i vanlig Storybook story, men fungerer fint i stories i docs og story åpnet i egen side; vil tro at problemet er `<iframe>`s og sånt, og vil dermed fungere i ekte applikasjoner.

ELSA1-535 Fikser problem med `<TableWrapper>` og SSR

---

.changeset/config.json

Interne pakker avhengige av spesifikk versjon av andre interne pakker bør ikke få bump på den; kun pakker som bruker workspace-protokoll skal få bump.

Fix: bump kun versjoner med workspace-protokoll

---

.changeset/lemon-jars-push.md
packages/dds-components/src/components/Select/Select.mdx
packages/dds-components/src/components/Select/Select.tsx

`<Select>` returnerte ikke riktig type, mest sannsynligvis pga bruk av `typeof SelectInner`. Dette påvirket også `ref`, da den ikke var støttet på komponenten.
Hva ble gjort:
- Fikser typen som returneres i `Select`.
- Eksponerer `type SelectForwardRefType<Option, IsMulti extends boolean>` til bruk med `useRef()` ved behov.
- Docs om bruk av `ref`.

ELSA1-373 Fikser `ref` og return-verdi i `<Select>`

---

CONTRIBUTING.md
README.md
packages/app-shell/README.md
packages/dds-components/README.md
packages/dds-formatting/README.md
packages/dds-tokens/README.md
packages/development-utils/README.md

Flytter all dokumentasjon som har med bidrag å gjøre fra design.domstol.no og `README.md` til `CONTRIBUTING.md`. Siden Zeroheight kan ha embedded .md-filer fra GitHub vil jeg legge den nye filen inn der vi hadde dokumentasjonen originalt. Rydder litt i alle READMEs i samme slengen.

ELSA1-537 Legger til `CONTRIBUTING.md`

---

packages/dds-components/src/components/Popover/Popover.context.tsx
packages/dds-components/src/components/Popover/Popover.spec.tsx
packages/dds-components/src/components/Popover/Popover.tsx
packages/dds-components/src/components/Popover/PopoverGroup.tsx
packages/dds-components/src/components/Tooltip/Tooltip.tsx
packages/dds-components/src/hooks/useFloatPosition.tsx

Team Sivil opplever at `<Popover>` lgger seg i hjørne og får floating styling på 0. Bruker samme implementasjon av `refs.setReference` som i `<Tooltip>` for å se om det hjelper. SIden komponenten er annerledes, bruker `context` for å sende riktige refs.
Rydder i `<Tooltip>` og andre filer i samme slengen.

ELSA1-542 Fikser Popover som legger seg i hjørne

---

.changeset/gold-cougars-collect.md
packages/dds-components/src/components/Popover/Popover.context.tsx
packages/dds-components/src/components/Popover/Popover.mdx
packages/dds-components/src/components/Popover/Popover.module.css
packages/dds-components/src/components/Popover/Popover.spec.tsx
packages/dds-components/src/components/Popover/Popover.stories.tsx
packages/dds-components/src/components/Popover/Popover.tsx
packages/dds-components/src/components/Popover/PopoverGroup.tsx

Komponenten var implementert på en utdatert måte og manglet støtte for kontrollert tilstand.
- Fjerner props `onCloseButtonClick` og `onTriggerClick`, legger til `onOpen` og `onClose` i `<PopoverGroup>`. På denne måten vil konsumentene kunne legge til callbacks basert på status på `<Popover>` uten å henge seg oppi detaljer rundt implementasjonen.
- Implementerer kontrollert tilstand. `<PopoverGroup>` kan nå ta inn `isOpen` og `setIsOpen` for bli kontrollert av konsumenten; hvis de ikke settes brukes intern håndtering. Legger også til `isInitiallyOpen`, som forteller om `<Popover>` vises på første render. Propen var tidligere kalt `isOpen`, så nå skiller vi mellom initial og kontrollert tilstand.
- Bytter navn på `title` prop til `header` i `<Popover>`. Det er mer riktig, og i tillegg …

ELSA1-543 Revamp av `<Popover>`-komponenten

---

.changeset/friendly-insects-explode.md
.changeset/pretty-impalas-occur.md
.changeset/stale-cars-wave.md
packages/dds-components/src/components/Drawer/Drawer.context.tsx
packages/dds-components/src/components/Drawer/Drawer.mdx
packages/dds-components/src/components/Drawer/Drawer.stories.tsx
packages/dds-components/src/components/Drawer/Drawer.tsx
packages/dds-components/src/components/Drawer/DrawerGroup.tsx
packages/dds-components/src/components/EmptyContent/EmptyContent.spec.tsx
packages/dds-components/src/components/EmptyContent/EmptyContent.tsx
packages/dds-components/src/components/InternalHeader/InternalHeader.tsx
packages/dds-components/src/components/Modal/Modal.stories.tsx
packages/dds-components/src/components/Modal/Modal.tsx
packages/dds-components/src/components/OverflowMenu/OverflowMenu.context.tsx
packages/dds-components/src/components/OverflowMenu/OverflowMenu.mdx
packages/dds-components/src/components/OverflowMenu/OverflowMenu.spec.tsx
packages/dds-components/src/components/OverflowMenu/OverflowMenu.stories.tsx
packages/dds-components/src/components/OverflowMenu/OverflowMenu.tsx
packages/dds-components/src/components/OverflowMenu/OverflowMenu.types.tsx
packages/dds-components/src/components/OverflowMenu/OverflowMenuGroup.tsx
packages/dds-components/src/components/OverflowMenu/components/OverflowMenuButton.tsx
packages/dds-components/src/components/OverflowMenu/components/OverflowMenuLink.tsx
packages/dds-components/src/components/Popover/Popover.context.tsx
packages/dds-components/src/components/ProgressTracker/ProgressTracker.stories.tsx
packages/dds-components/src/components/SplitButton/SplitButton.tsx
packages/dds-components/src/hooks/useFloatPosition.tsx

Standardisering av bruk av flate-komponenter.
- Revamp av `<OverflowMenu>`.
- Fjerner prop `onToggle` i `<OverflowMenuGroup>`. Komponenten blir standardisert og bruker kun `onClose` og `onOpen`.
- Implementerer kontrollert tilstand. `<OverflowMenuGroup>` kan nå ta inn `isOpen` og `setIsOpen` props for bli kontrollert av konsumenten; hvis de ikke settes brukes intern håndtering. Legger også til `isInitiallyOpen`, som forteller om `<OverflowMenu>` vises på første render.
- Fjerner props fra `<OverflowMenu>` som ble satt av forelder: `isOpen`, `anchorRef`, `onClose`, `onToggle`, `id` og implementerer React Context istedet. Vi unngår dermed rotet med props konsumenter ikke "får lov" til å sette. `<OverflowMenuGroup>` er dermed obigatorisk å bruke.
- Revamp av `<Drawer>`.
- Implementerer …

ELSA1-547 Revamp av flate-komponenter

---

.changeset/young-doors-explain.md
packages/dds-components/src/components/Tabs/AddTabButton.tsx
packages/dds-components/src/components/Tabs/Tab.tsx
packages/dds-components/src/components/Tabs/Tabs.context.tsx
packages/dds-components/src/components/Tabs/Tabs.module.css
packages/dds-components/src/components/Tabs/Tabs.stories.tsx
packages/dds-components/src/components/Tabs/Tabs.tsx

Med `'medium'` og `'small'` som støttede verdier. Bruker `'small'` som default. Justerer også på spacing i begge variantene.

ELSA1-545 Støtte for `size` prop i `<Tabs>`

---

.changeset/shaggy-socks-smell.md
packages/dds-components/src/components/Tabs/TabList.tsx
packages/dds-components/src/components/Tabs/Tabs.spec.tsx

Støtte for `onClick` prop for individuelle `<Tab>` delkomponenter i `<Tabs>`.

ELSA1-546 `onClick` støtte i `<Tab>`

---

.changeset/wise-hornets-pull.md
packages/dds-components/src/components/Popover/Popover.stories.tsx
packages/dds-components/src/components/Popover/Popover.tsx
packages/dds-components/src/hooks/useOnClickOutside.tsx

Støtte for kontrollert `<Popover>` uten `<PopoverGroup>` i corner cases. Behov hos Beramming.

ELSA1-558 Støtte for kontrollert `<Popover>`

---

.changeset/long-rockets-wash.md
packages/dds-components/src/components/InputStepper/InputStepper.spec.tsx
packages/dds-components/src/components/InputStepper/InputStepper.tsx

Denne PRen fikser en bug der `<InputStepper>` ikke fikk satt readOnly. Legger også til tester for readOnly og disabled

ELSA1-565 Bugfix `<InputStepper>` readOnly & added tests

---

packages/dds-components/src/components/Accordion/AccordionBody.tsx
packages/dds-components/src/components/Accordion/AccordionHeader.tsx
packages/dds-components/src/components/BackLink/BackLink.tsx
packages/dds-components/src/components/Card/CardExpandable/CardExpandableBody.tsx
packages/dds-components/src/components/Card/CardExpandable/CardExpandableHeader.tsx
packages/dds-components/src/components/Drawer/Drawer.tsx
packages/dds-components/src/components/Drawer/DrawerGroup.tsx
packages/dds-components/src/components/OverflowMenu/OverflowMenuGroup.tsx
packages/dds-components/src/components/Pagination/Pagination.tsx
packages/dds-components/src/components/Popover/Popover.tsx
packages/dds-components/src/components/Popover/PopoverGroup.tsx
packages/dds-components/src/components/Select/SelectComponents.tsx
packages/dds-components/src/components/SelectionControl/Checkbox/Checkbox.tsx
packages/dds-components/src/components/Table/normal/Table.stories.tsx
packages/dds-components/src/components/Tabs/TabList.tsx
packages/dds-components/src/components/helpers/AccordionBase/AccordionContext.tsx
packages/dds-components/src/utils/index.ts
packages/dds-components/src/utils/object.tsx

Bruker type argument  med `ReactElement`, sjekker for tomt objekt for context, fikser andre mindre instanser.

ELSA1-568 Fjerner unødvendig type casting

---

.storybook/preview.tsx
packages/dds-components/src/hooks/useRoveFocus.stories.tsx
packages/development-utils/src/EnvironmentBannerProvider/EnvironmentBannerProvider.mdx
packages/development-utils/src/EnvironmentBannerProvider/EnvironmentBannerProvider.stories.tsx
stories/Tokens/Tokens.stories.tsx
stories/Tokens/TypographyBase.stories.tsx

Enkelte stories skal ikke ha theme-toggle: tokens, hooks, EnvironmentBannerProvider. Implementerer støtte for å kunne slå den av.
Før:
Etter:

ELSA1-575 Slår av temastyring i stories som ikke trenger det

---

.changeset/clean-olives-punch.md
packages/dds-formatting/src/beloep/formatBeloep.test.ts
packages/dds-formatting/src/beloep/formatBeloep.ts
packages/dds-formatting/src/beloep/formatInputBeloep.test.ts
packages/dds-formatting/src/beloep/formatInputBeloep.ts
packages/dds-formatting/src/beloep/index.ts
packages/dds-formatting/src/index.ts

Implementerer formateringsfunksjoner for beløp, `formatBeloep()` for tall og `formatInputBeloep()` for typisk tekstlig input, son ekskluderer valuta.

ELSA1-576 Formatering av beløp

---

.changeset/empty-worlds-buy.md
packages/dds-components/src/components/Tabs/Tab.tsx
packages/dds-components/src/components/Tabs/TabList.tsx
packages/dds-components/src/components/Tabs/Tabs.mdx

Fikser bug der `htmlProps`-prop ikke ble satt og setter standardverdien `type='button'` i `<Tab>`. På denne måten vil ikke bytting mellom faner trigge submit hvis `<Tabs>` ligger i `<form>`.

ELSA1-581 `htmlProps` blir ikke satt i `<Tab>`

---

.changeset/few-crabs-pick.md
packages/dds-components/src/components/Popover/Popover.stories.tsx
packages/dds-components/src/components/Popover/Popover.tsx

Tillater bruk av popover inne i scrollable container, slik at man ikke risikerer at innhold i popover blir skjult av scroll
Eksemp
el uten portal:
Eksempel med portal:

ELSA-582 Mulighet for rendre popover i portal

---

.changeset/shaggy-snails-argue.md
packages/dds-components/src/components/OverflowMenu/OverflowMenu.module.css
packages/dds-components/src/components/OverflowMenu/OverflowMenu.stories.tsx
packages/dds-components/src/components/OverflowMenu/OverflowMenu.types.tsx
packages/dds-components/src/components/OverflowMenu/components/OverflowMenuButton.tsx
packages/dds-components/src/components/helpers/styling/utilStyles.module.css

Støtte for props `loading` og `loadingTooltip` i `<OverflowMenuButton>`. Rendrer spinner med tilhørende toolitp ved `loading`; Gjør initial innhold usynlig, men fortsatt tilgjengelig for skjermleser slik at den kan leses opp i kombinasjon med tooltip.

ELSA1-584 loading state i OverflowMenuButton

---

.changeset/lazy-apes-brush.md
.changeset/tender-hairs-sing.md
packages/dds-components/src/components/Typography/Legend/Legend.tsx
packages/dds-components/src/components/Typography/Typography/Typography.tsx
packages/dds-components/src/components/Typography/typographyStyles.module.css
packages/dds-components/stories/patterns/Form.stories.tsx

Ny prop i `<Legend>`: `typoghraphyType`. Den støtter typografistilier for overskrifter. Brukes når komponenten trenger størrelsen tilpasset etter overskriftshierarki ellers på siden.
Fjerner også fast spacing på bunnen i `<Legend>` ved bruk av `withMargins` prop; den arver nå spacing fra valgt typografistil.
Fikser Form pattern til å bruke `typoghraphyType` i `<Legend>`.

ELSA1-592 Støtte for `typographyType` i `<Legend>`

---

packages/dds-components/src/components/Footer/FooterLogo.tsx

Fikser bug introdusert i forrige PR, der props `height` og `width` ble tolket som CSS props.

Fix: logo i Footer får bredde og høyde

---

.changeset/wicked-goats-warn.md
packages/dds-components/src/components/DetailList/DetailList.context.tsx
packages/dds-components/src/components/DetailList/DetailList.module.css
packages/dds-components/src/components/DetailList/DetailList.spec.tsx
packages/dds-components/src/components/DetailList/DetailList.stories.tsx
packages/dds-components/src/components/DetailList/DetailList.tsx
packages/dds-components/src/components/DetailList/DetailListRow.tsx

Propen gjør om rader (`<DetailListRow>`) til kolonner, slik at den er responsiv.

ELSA1-597 `smallScreenBreakpoint` prop i `<DetailList>`

---

.changeset/shiny-loops-hunt.md
packages/dds-components/src/components/Search/Search.module.css
packages/dds-components/src/components/Search/Search.stories.tsx
packages/dds-components/src/components/Search/Search.tsx

Støtte for responsiv `width` til å begynne med, da den støttet bare HTML `width` attributt som egentlig ikke fungerer; og responsiv støtte som i alle andre inputkomponenter.

ELSA1-602 Støtte for responsiv `width` prop i `<Search>`

---

packages/dds-components/src/components/Typography/typographyStyles.module.css

Simplifiserer koden for å sjekke om det hjelper med at `:visited` ikke fungerer i Chrome på Mac.

ELSA1-601 Link visited i Chrome, Mac

---

.changeset/tired-spiders-rule.md
packages/dds-components/src/components/LocalMessage/LocalMessage.module.css
packages/dds-components/src/components/LocalMessage/LocalMessage.tsx

Endrer layout i `LocalMessage` slik at ikon legger seg på toppen ved flere linjer med tekst. Fikser andre små feil som avstander og størrelse på lukkeknapp.
Før:
Etter: 

ELSA1-583 Ikon i `<LocalMessage>` alignet på toppen

---

.changeset/cool-owls-take.md
.changeset/thirty-shoes-type.md
packages/dds-components/src/components/Search/Search.module.css
packages/dds-components/src/components/Search/Search.stories.tsx
packages/dds-components/src/components/Search/Search.tsx
packages/dds-components/src/components/Search/SearchSuggestions.tsx

Støtter prop `showIcon`. Fjerner i samme slengen unødvendig nøstet div når søkeknappen ikke er der, og migrerer relevante delkomponenter til layout primitives.
Justerer på avstander da de var feil.

ELSA1-600 Støtte for å skjule ikon i `<Search>`

---

packages/dds-components/src/components/FileUploader/FileUploader.spec.tsx

Noen tester failet i PRer som ikke rørte testkoden. Fikser slik at det blir konsekvent oppførsel.

ELSA1-603 Fikser uforutsigbar test i `<FileUploader>`

---

.changeset/clear-pants-stick.md
packages/dds-components/src/components/ProgressTracker/ProgressTracker.module.css
packages/dds-components/src/components/ProgressTracker/ProgressTracker.stories.tsx
packages/dds-components/src/components/ProgressTracker/ProgressTracker.tsx
packages/dds-components/src/components/helpers/StylelessList/StylelessList.tsx

Via ny prop: `direction`. Komponenten er fortsatt vertikal som default.

ELSA1-593 Støtte for horisontal `<ProgressTracker>`

---

.changeset/tangy-points-beg.md
packages/dds-components/src/components/SelectionControl/Checkbox/Checkbox.tsx
packages/dds-components/src/components/SelectionControl/Checkbox/CheckboxGroup.tsx
packages/dds-components/src/components/SelectionControl/RadioButton/RadioButtonGroup.tsx
packages/dds-components/src/components/SelectionControl/SelectionControl.styles.tsx
packages/dds-components/src/types/Booleanish.ts

Fikser bug der styling ikke ble satt.
Fikser også feil størrelse på readonly-ikon i gruppeledetekst, og standardiserer den via `<GroupLabel>` JSX element.

ELSA1-611 Manglende layout styling i `<RadioButton>`

---

.changeset/bright-snakes-tickle.md
packages/dds-components/src/components/ProgressTracker/ProgressTracker.context.tsx
packages/dds-components/src/components/ProgressTracker/ProgressTracker.module.css
packages/dds-components/src/components/ProgressTracker/ProgressTracker.spec.tsx
packages/dds-components/src/components/ProgressTracker/ProgressTracker.tsx
packages/dds-components/src/components/ProgressTracker/ProgressTrackerItem.tsx
packages/dds-components/src/components/helpers/StylelessList/StylelessList.tsx

- `<nav>` wrapper for navigasjon
- fikser bug der egen `aria-label` ikke var støttet
- bedre default `aria-label`
- bedre usynlig knappetekst for skjermleser
- fikser ugyldig HTML; tar i bruk `::after` for enkel connector istedenfor `<div>`

ELSA1-574 Bedre UU i `<ProgressTracker>`

---

.changeset/ready-pandas-shine.md
packages/dds-components/src/components/OverflowMenu/OverflowMenu.spec.tsx
packages/dds-components/src/components/OverflowMenu/OverflowMenu.stories.tsx
packages/dds-components/src/components/OverflowMenu/OverflowMenu.types.tsx
packages/dds-components/src/components/OverflowMenu/components/OverflowMenuButton.tsx

Støtte for async funksjonkall med `onClickAsync` prop i `<OverflowMenuButton>`, slik at menyen er fortsatt åpen under loading.

ELSA1-607 Støtte for async funksjon i `<OverflowMenuButton>`

---

.changeset/big-donkeys-attend.md
.changeset/calm-frogs-beg.md
packages/dds-components/src/components/Card/Card.module.css
packages/dds-components/src/components/Card/Card.stories.tsx
packages/dds-components/src/components/Card/CardSelectionControl/CardSelectable.stories.tsx
packages/dds-components/src/components/Card/CardSelectionControl/CardSelectable.tsx
packages/dds-components/src/components/SelectionControl/Checkbox/Checkbox.tsx
packages/dds-components/src/components/SelectionControl/RadioButton/RadioButton.tsx
packages/dds-components/src/components/SelectionControl/RadioButton/RadioButtonGroup.stories.tsx
packages/dds-components/src/components/SelectionControl/SelectionControl.module.css
packages/dds-components/src/components/SelectionControl/SelectionControl.styles.tsx

Små justeringer i styling i `<SelectableCard>`:
- selected-bakgrunn ved `checked`,
- ingen ramme ved `disabled`/`readOnly` kombinert med `checked`, 
- disabled-bakgrunn i selection control ved `disabled`/`readOnly`.
Generelt for selection control: Hover styling overskriver nå error-styling i `Checkbox>` og `<RadioButton>`.
Legger også til CardSelectable i overview-story og refaktorerer `SelectionControl.module.css`.
Før:
Etter (subtile forskjeller):

ELSA1-624 Styling-justeringer i `<CardSelectable>`

---

.changeset/violet-ads-grow.md
packages/dds-components/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
packages/dds-components/src/components/Card/CardSelectionControl/CardSelectableGroup.stories.tsx
packages/dds-components/src/components/FileUploader/FileUploader.tsx
packages/dds-components/src/components/Footer/Footer.stories.tsx
packages/dds-components/src/components/InlineButton/InlineButton.stories.tsx
packages/dds-components/src/components/InlineEdit/InlineEdit.utils.tsx
packages/dds-components/src/components/ProgressTracker/ProgressTrackerItem.tsx
packages/dds-components/src/components/Search/Search.tsx
packages/dds-components/src/components/Table/collapsible/CollapsibleRow.tsx
packages/dds-components/src/components/Table/collapsible/CollapsibleTable.stories.tsx
packages/dds-components/src/components/Toggle/Toggle.tsx
packages/dds-components/src/components/VisuallyHidden/VisuallyHidden.spec.tsx
packages/dds-components/src/components/VisuallyHidden/VisuallyHidden.stories.tsx
packages/dds-components/src/components/VisuallyHidden/VisuallyHidden.tsx
packages/dds-components/src/components/date-inputs/DatePicker/Calendar/CalendarGrid.tsx
packages/dds-components/src/storybook/helpers.tsx
stories/Tokens/utils/ColorsGenerator.tsx
stories/Tokens/utils/ShadowsGenerator.tsx

Utvider `<VisuallyHidden>` sin `as` prop til å støtte valgfritt element. Propen er ikke lenger påkrevd og komponenten returnerer `<span>` som default.

ELSA1-619 Polymorfi i `<VisuallyHidden>`

---

.changeset/smart-times-smoke.md
packages/dds-components/src/components/Accordion/AccordionHeader.tsx
packages/dds-components/src/components/Card/CardExpandable/CardExpandableHeader.tsx
packages/dds-components/src/components/CookieBanner/CookieBanner.mdx
packages/dds-components/src/components/CookieBanner/CookieBanner.spec.tsx
packages/dds-components/src/components/CookieBanner/CookieBanner.stories.tsx
packages/dds-components/src/components/CookieBanner/CookieBanner.tsx
packages/dds-components/src/components/Feedback/RatingComponent.tsx
packages/dds-components/src/components/Icon/icons.stories.tsx
packages/dds-components/src/components/InlineButton/InlineButton.tsx
packages/dds-components/src/components/Search/SearchSuggestionItem.tsx
packages/dds-components/src/components/Table/collapsible/CollapsibleRow.tsx
packages/dds-components/src/components/Table/normal/SortCell.tsx
packages/dds-components/src/components/helpers/StylelessButton/StylelessButton.tsx
packages/dds-components/src/components/helpers/StylelessButton/index.tsx
packages/dds-components/src/components/helpers/index.ts

Brukes til sammentrukket versjon av banneren på siden med detaljer om informasjonskapsler. Detaljer i retningerlinjer i mdx-fila.
Lagde også StylelessButton da jeg trodde den var relevant; var ikke det likevel, men den er fortsatt nytting og jeg migrerte relevante knapper på tvers av biblioteket.

ELSA1-628 Ny prop i `<CookieBanner>`: `collapsedBreakpoint`.

---

.changeset/happy-lines-add.md
packages/dds-components/src/components/TextInput/TextInput.module.css
packages/dds-components/src/components/date-inputs/common/DateInput.module.css

Fjerner CSS som overskriver propen. Fjerner også ubrukt width-relatert kode  i `<TextInput>` CSS.

ELSA1-636 `<DatePicker>` blir ikke påvirket av `width` prop

---

.changeset/real-moments-know.md
packages/dds-components/src/components/SelectionControl/Checkbox/Checkbox.spec.tsx
packages/dds-components/src/components/SelectionControl/SelectionControl.module.css

Fikser bug der `<Checkbox>` fikk indeterminate-styling selv om `indeterminate` prop var satt til `false`.
Slenger på en manglende test som sjekker om indeterminate-tilstand blir satt på `<input>`.

ELSA1-637 `<Checkbox>` indeterminate-styling bug

---

.changeset/deep-actors-work.md
packages/dds-components/src/components/Select/Select.tsx
packages/dds-components/src/components/Select/SelectComponents.tsx

Custom `<DDSControl>` delkomponent ble sendt inn slik i `<ReactSelect>`: `Control: props => DDSControl(props, componentSize, readOnly, icon, dataTestId)`. Det forvirret intern memoization og fokushåndtering. Fikser bugen ved å bruke memo og factory, så delkomponenten kan sendes inn slik: `Control: DDSControl(componentSize, readOnly, icon, dataTestId)`.

ELSA1-610 `<Select>` lukker dropdown når options endrer seg dynamisk

---

.changeset/eleven-paths-lay.md
packages/dds-components/src/components/TextArea/TextArea.tsx

`<TextArea>` blir nå mindre når brukeren fjerner tekst; før endret størrelsen seg kun når brukeren skrev mer tekst, nå endres størrelsen i begge tilfeller. Grunnen til gamle oppførselen var at høyden var alltid større enn `scrollHeight`; å nullstille til `'auto'` først tillater beregning basert på nåværende tekst.
https://github.com/user-attachments/assets/dd19ca70-c2fb-4bd1-a2fc-dfb90d672c0d

ELSA1-590 `<TextArea>` bli mindre når tekst fjernes

---

.changeset/chubby-buckets-pay.md
packages/dds-components/src/components/Button/Button.tsx

Størrelse og spacing på spinner skal følge tekst/knapp den erstatter.
Før:
Etter:

ELSA1-635 Fikser størrelse på spinner i `<Button>`ved loading

---

.changeset/small-buckets-play.md
packages/dds-components/src/components/CookieBanner/CookieBanner.tsx
packages/dds-components/src/components/InternalHeader/InternalHeader.tsx
packages/dds-components/src/components/Pagination/Pagination.tsx
packages/dds-components/src/components/PhoneInput/PhoneInput.tsx
packages/dds-components/src/components/VisuallyHidden/VisuallyHidden.stories.tsx
packages/dds-components/src/components/helpers/Input/Input.types.tsx
packages/dds-components/src/components/helpers/Input/Input.utils.tsx
packages/dds-components/src/components/layout/common/utils.tsx
packages/dds-components/stories/patterns/Form/Form.mdx
packages/dds-components/stories/patterns/Form/Form.stories.tsx
packages/dds-components/stories/patterns/introduction.mdx

Implementerer ferdig eksempler for skjema-mønstre: vanlig, med steg og forsøk på å forlate påbegynt skjema. Skriver ferdig docs for disse samt for mønstre generelt. Docs er tilgjengelige under "Patterns": https://elsa1-540-form-pattern.designsystem.pages.dev/?path=/docs/patterns-introduction--docs
Andre endringer gjort for å utbedre bruk av mønstre:
- Justerer på hvordan `width` prop fungerer på skjemakomponenter. Hvis bredde settes kun på enkelte brekkpunkter vil resterende brekkpunkter få default bredde definert i komponenten. Før fikk utelatte brekkpunkter ingen definert bredde, og dermed utforutsigbar bredde. Kan potensielt føre til endringer i layout. Påvirker komponentene `<TextInput>`, `<Select>`, `<PhoneInput>`, `<ProgressBar>`, `<NativeSelect>`, `<TextArea>`, `<DatePicker>`, …

ELSA1-540 Mønster: skjema

---

.github/dependabot.yml

Typescript følger ikke semver og fikk egen gruppe i `dependabot.yml`, men den får ikke egen PR ved ny versjon. Oppdaterer config for å se om den får det.

ELSA1-665 Egen gruppe for Typescript i `dependabot.yml`

---

packages/dds-components/src/components/Select/NativeSelect/NativeSelect.tsx

HTML-attributtet `read-only` er ikke standard for enkelte elementer som `<select>`, men vi implementerer standard oppførsel for slike skjemaelementer; oppdaterer JSDoc slik at den gjenspeiler det, samt viser propen riktig i tabellen i Storybook docs.

ELSA1-677 JSDoc for `readOnly` i `NativeSelect`

---

.changeset/nice-tips-yawn.md
packages/dds-components/src/components/FavStar/FavStar.stories.tsx
packages/dds-components/src/components/Icon/Icon.stories.tsx
packages/dds-components/src/components/Select/NativeSelect/NativeSelect.module.css
packages/dds-components/src/components/Select/NativeSelect/NativeSelect.tsx
packages/dds-components/src/components/Tabs/Tabs.stories.tsx
packages/dds-components/src/components/ToggleBar/ToggleBar.stories.tsx
packages/dds-components/src/components/helpers/Input/Input.module.css
packages/dds-components/src/storybook/helpers.tsx
stories/Playground/FormComponentsTesting.stories.tsx

Fikser spacing slik den er lik `<Select>` og størrelse på tømmeknapp. Refaktorerer også story for testing om komponenter ser likt ut, gjør den mer selvforklarende.

ELSA1-642 Chevron spacing i `<NativeSelect>`

---

.changeset/heavy-results-dress.md
.changeset/solid-ways-dream.md
packages/dds-components/src/components/TextInput/TextInput.mdx
packages/dds-components/src/components/TextInput/TextInput.module.css
packages/dds-components/src/components/TextInput/TextInput.stories.tsx
packages/dds-components/src/components/TextInput/TextInput.tsx
packages/dds-components/src/components/TextInput/TextInput.types.tsx
packages/dds-components/src/components/date-inputs/DatePicker/DateField/CalendarButton.tsx
packages/dds-components/src/utils/icon.ts

Fikser feil spacing mellom ikon og tekst.
Før: 
Etter:
I samme slengen:
- Fikser bug der prefiks og suffiks overlappet med tekst i `<TextInput>`.
- Ekskluderer native HTML attributt `prefix` fra `type TextInputProps`. Den er ikke relevant, og da krangler den ikke med custom  `prefix` prop i args-tabellen i docs.
- Migrerer `TextInput.mdx` til å bruke `<Tabs>` med relevante eksempler. Skal gradvis migrere alle relevante komponenter.
- Fikser typo i `const prefixPaddingInlineStart`.
- Refaktorerer `getFormInputIconSize()` for bedre gjenbruk; tar den i bruk i `<DatePicker>`.

ELSA1-681 Fikser feil spacing i `<TextInput>`

---

.changeset/brave-jokes-press.md
packages/dds-components/src/components/date-inputs/common/DateInput.tsx

Segment for dag og måned aksepterte ikke ledende 0, og da kunne bruker ikke skrive f.eks. "01" for å få januar måned.
Feilen var at `fieldProps` og `ref` ble satt på feil wrapper; flytter de til fordelderen til segmentene.

ELSA1-686 Ledende 0 bug i `<DatePicker>`

---

.changeset/fuzzy-bobcats-obey.md
packages/dds-components/src/components/helpers/ClearButton/ClearButton.tsx
packages/dds-components/src/components/helpers/InlineIconButton/InlineIconButton.tsx

Default er "submit", noe som gjør at skjema blir submitted når ClearButton trykkes
_Denne PRen endrer..._

ELSA1-691: Sett type til "button" for ClearButton og InlineIconButton

---

stories/Tokens/Tokens.stories.tsx
stories/Tokens/utils/functions.tsx

Gjør visningen av tokens i Storybook oversiktlig ved å bruke `<Tabs>`. Gjelder `borderRadius` og `typography`.
Ser slik ut:

ELSA1-688 Vise theme-avhengige tokens i `<Tabs>`

---

packages/dds-components/src/components/LocalMessage/LocalMessage.mdx
packages/dds-components/src/components/LocalMessage/LocalMessage.stories.tsx

Lager et eksempel som bygger opp riktig layout. Migrerer `<LocalMessage>` til `<Tabs>` visning i samme slengen.

ELSA1-379 `<LocalMessage>` Storybook eksempel med ekstra knapp

---

.changeset/all-clocks-watch.md
.changeset/four-poems-juggle.md
.changeset/purple-owls-post.md
packages/dds-components/src/components/FileUploader/FileUploader.tsx
packages/dds-components/src/components/InputStepper/InputStepper.module.css
packages/dds-components/src/components/InputStepper/InputStepper.spec.tsx
packages/dds-components/src/components/InputStepper/InputStepper.stories.tsx
packages/dds-components/src/components/InputStepper/InputStepper.tsx
packages/dds-components/src/components/PhoneInput/PhoneInput.tsx
packages/dds-components/src/components/ProgressBar/ProgressBar.tsx
packages/dds-components/src/components/Search/Search.tsx
packages/dds-components/src/components/Select/NativeSelect/NativeSelect.tsx
packages/dds-components/src/components/Select/Select.tsx
packages/dds-components/src/components/SelectionControl/Checkbox/CheckboxGroup.tsx
packages/dds-components/src/components/SelectionControl/RadioButton/RadioButtonGroup.tsx
packages/dds-components/src/components/SelectionControl/SelectionControl.styles.tsx
packages/dds-components/src/components/TextArea/TextArea.tsx
packages/dds-components/src/components/TextInput/TextInput.tsx
packages/dds-components/src/components/ToggleButton/ToggleButtonGroup.tsx
packages/dds-components/src/components/Typography/Label/Label.utils.tsx
packages/dds-components/src/components/Typography/typographyStyles.module.css
packages/dds-components/src/components/date-inputs/common/DateInput.tsx
packages/dds-components/src/components/helpers/Input/Input.module.css

Implementasjonen var ulik og rotete på tvers, lager en render-funksjon som gjør det likt overalt.
- Endrer effekten av `withMargins` prop i `<Label>`. Den får ikke lenger margin `1em` topp og bunn, men `dds-spacing-x0-125` kun bunn. Kan resultere i endringer i layout.
- Standardiserer spacing mellom ledetekst og input på tvers av komponenter. Påvirker `<TextInput>`, `<TextArea>`, `<DatePicker>`, `<TimePicker>`, `<Select>`, `<NativeSelect>`, `<CheckboxGroup>`, `<RadioButtonGroup>`, `<ToggleButtonGroup>`, `<ProgressBar>`, `<Search>`, `<FileUploader>`, `<InputStepper>`, `<PhoneInput>`.
- I samme slengen: refaktorerer `<InputStepper>` og utbedrer usynlige ledetekster.

ELSA1-598 Standardisering av spacing mellom ledetekst og input

---

.changeset/all-schools-sin.md
packages/dds-components/src/components/date-inputs/DatePicker/DateField/DateField.tsx
packages/dds-components/src/components/date-inputs/DatePicker/DateField/DateField.utils.tsx
packages/dds-components/src/components/date-inputs/DatePicker/DateField/DateSegment.tsx
packages/dds-components/src/components/date-inputs/DatePicker/DatePicker.tsx
packages/dds-components/src/components/date-inputs/DatePicker/constants.ts
packages/dds-components/src/components/date-inputs/TimePicker/TimePicker.tsx

Språket hentes fra `<DdsProvider>`, bruker 'nb-NO' som standard. Tar hånd om oversettelser mens datoformatet alltid er norsk.

ELSA1-702 Støtte for locale i `<DatePicker>` og `<TimePicker>`

---

.changeset/mean-icons-begin.md
.changeset/open-eagles-stop.md
.changeset/tall-owls-hide.md
packages/dds-components/src/components/FileUploader/File.tsx
packages/dds-components/src/components/FileUploader/FileUploader.mdx
packages/dds-components/src/components/FileUploader/FileUploader.module.css
packages/dds-components/src/components/FileUploader/FileUploader.spec.tsx
packages/dds-components/src/components/FileUploader/FileUploader.stories.tsx
packages/dds-components/src/components/FileUploader/FileUploader.tsx
packages/dds-components/src/components/FileUploader/useFileUploader.ts
packages/dds-components/src/components/FileUploader/utils.ts
packages/dds-components/src/types/Surface.tsx
packages/dds-components/src/utils/readonlyEventHandlers.tsx

Komponenten kunne få disse props uten noe effekt. Implementerer de på ordentlig:
- Hvis komponenten har ingen filer ser man kun ledetekst og ingen filer-tekst. ved `readOnly` kan `<input>` få fokus og teksten er tilgjengelig.
- Hvis filer er lastet opp ser man ledetekst + filliste tilgjengelig for skjermlesere..
Gjort i samme slengen:
- Utbedrer tester.
- Legger til manglende oversettelser.
- Migrerer `FileUploader.mdx` til visning med `<Tabs>`.
- Utvider `background` prop i `<Paper>` til å støtte `'surface-field-disabled'`.

ELSA1-698 Støtte for `disabled` og `readOnly` i `<Fileuploader>`

---

.changeset/calm-results-drive.md
packages/dds-components/src/components/Pagination/Pagination.spec.tsx
packages/dds-components/src/components/Pagination/Pagination.stories.tsx
packages/dds-components/src/components/Pagination/Pagination.tsx

Komponenten bruker nå `useControllableState`-hooken for å støtte både kontrollert og ukontrollert bruk. Den nye `activePage`-propen lar utviklere styre aktiv side utenfra, mens eksisterende bruk med `defaultActivePage` fortsatt fungerer som før (ukontrollert).

Legge til støtte for kontrollert state i `<Pagination>`

---

CONTRIBUTING.md

Oppdaterer informasjon om linking av dds-pakke i andre prosjekt. Navnet på pakken må være tilsvarende det som er satt opp som `name` i `package.json`.

Oppdaterer informasjon om linking av pakke
