components/src/components/SplitButton/SplitButton.stories.tsx, components/src/components/SplitButton/SplitButton.tokens.ts, components/src/components/SplitButton/SplitButton.tsx
Legger til `purpose`-prop for `SplitButton` - samme som for `Button`.
=> Flere varianter av SplitButton

components/src/components/ProgressTracker/ProgressTracker.tokens.tsx, components/src/components/Table/Table.stories.tsx, components/src/components/TextInput/TextInput.styles.tsx, components/src/components/TextInput/TextInput.tsx, components/src/components/Typography/Typography/Typography.tsx
- fjerner ubrukte verdier
- endrer en story tittel ti PascalCase
=> Fikser warnings fra verify:*lint

packages/formatting/package.json
Publiserer formatteringfunksjon for fasttelefon-/faksnummer
=> Ny versjon 1.1.0 av dds-formatting

packages/components/src/components/FormGenerator/FormGenerator.tsx
Fiks problem ved at kun felt med endringer ble returnert i onChange. Nå returneres hele staten ved hver onChange.
=> Fix: Sett initiell state i FormGenerator

.github/workflows/pull-request.yml, .github/workflows/release.yml, package.json
=> oppdater release CI til å bruke changesets action

.changeset/healthy-shoes-shop.md, packages/components/src/icons/tsx/doubleChevronLeft.tsx, packages/components/src/icons/tsx/doubleChevronRight.tsx, packages/components/src/icons/tsx/index.ts
=> Nye chevron ikoner

package-lock.json, packages/components/package.json
Reverts domstolene/designsystem#601
=> Revert "Bump @storybook/manager-webpack5 from 6.5.15 to 6.5.16"

.changeset/proud-pillows-kneel.md, packages/components/src/components/EmptyContent/EmptyContent.stories.mdx, packages/components/src/components/EmptyContent/EmptyContent.stories.tsx, packages/components/src/components/EmptyContent/EmptyContent.tsx
Komponent som viser en tom tilstand.
=> ELSA1-223 Legger til EmptyContent

.changeset/dry-waves-brush.md, package-lock.json, packages/page-generator/package.json, packages/page-generator/vite.config.ts, turbo.json
Fikser "Invalid hook"-feilen i `@norges-domstoler/dds-page-generator`-pakken.
**Kjent feil**
`dds-page-generator`-pakken lar seg i bruke i `testapp` da `testapp` kjører moderne React 18 streaming SSR. `styled-components` ser ikke ut til å ha støtte for dette enda (ref.: https://github.com/styled-components/styled-components/issues/3658)
=> Fix page generator build

.changeset/spicy-adults-refuse.md, packages/components/src/components/ProgressTracker/ProgressTracker.stories.tsx, packages/components/src/components/ProgressTracker/ProgressTracker.tokens.tsx, packages/components/src/components/ProgressTracker/ProgressTracker.tsx, packages/components/src/components/ProgressTracker/ProgressTrackerItem.tsx
Ønsket å gjenbruke CardAccordion da det overlappet veldig mye med design av mobilversjonen
=> ELSA1-192 ProgressTracker Mobile

.changeset/fair-pianos-love.md, packages/components/src/components/FileUploader/FileUploader.stories.mdx, packages/components/src/components/FileUploader/FileUploader.tsx, packages/components/src/components/FileUploader/useFileUploader.ts
Legger til value prop på FileUploader-komponent for å kunne kontrollere komponenten fra utsiden.
=> ELSA1-238: Legger til value prop på FileUploader-komponent

.changeset/spicy-adults-refuse.md, packages/components/src/components/ProgressTracker/ProgressTracker.stories.tsx, packages/components/src/components/ProgressTracker/ProgressTracker.tokens.tsx, packages/components/src/components/ProgressTracker/ProgressTracker.tsx, packages/components/src/components/ProgressTracker/ProgressTrackerItem.tsx
Reverts domstolene/designsystem#656
Reverter for å release andre endringer
=> Revert "ELSA1-192 ProgressTracker Mobile"

.changeset/spicy-adults-refuse.md, packages/components/src/components/ProgressTracker/ProgressTracker.stories.tsx, packages/components/src/components/ProgressTracker/ProgressTracker.tokens.tsx, packages/components/src/components/ProgressTracker/ProgressTracker.tsx, packages/components/src/components/ProgressTracker/ProgressTrackerItem.tsx
Reverts domstolene/designsystem#660
Legger endringene tilbake etter release av de andre endringene
=> Revert "Revert "ELSA1-192 ProgressTracker Mobile""

.changeset/spicy-adults-refuse.md, packages/components/src/components/ProgressTracker/ProgressTracker.stories.tsx, packages/components/src/components/ProgressTracker/ProgressTracker.tokens.tsx, packages/components/src/components/ProgressTracker/ProgressTracker.tsx, packages/components/src/components/ProgressTracker/ProgressTrackerItem.tsx
Reverter progress tracker igjen mens vi venter på nødvendige endringer
=> Revert progress tracker

.changeset/strange-parrots-press.md, packages/components/src/components/BackLink/BackLink.stories.mdx, packages/components/src/components/BackLink/BackLink.stories.tsx, packages/components/src/components/BackLink/BackLink.tokens.tsx, packages/components/src/components/BackLink/BackLink.tsx, packages/components/src/components/BackLink/index.tsx, packages/components/src/components/Breadcrumbs/Breadcrumbs.stories.mdx, packages/components/src/components/Breadcrumbs/Breadcrumbs.stories.tsx, packages/components/src/components/Breadcrumbs/Breadcrumbs.tsx, packages/components/src/index.ts
Løser disse to JIRA-oppgavene:
- https://domstol.atlassian.net/browse/ELSA1-242?atlOrigin=eyJpIjoiM2VmYTU3Yjg5ODk0NGQ1Y2I1YjI3MmMyMzJhMWIwNjgiLCJwIjoiaiJ9
- https://domstol.atlassian.net/browse/ELSA1-243?atlOrigin=eyJpIjoiZGRjNDc0NWQ0NjI1NGI4OWE3M2JlYzY4NTMyMzMzMmIiLCJwIjoiaiJ9
=> Elsa1 242 skill ut backbutton fra breadcrumb

package-lock.json, packages/components/package.json, packages/components/src/components/Button/Button.spec.tsx, packages/components/src/components/Chip/Chip.spec.tsx, packages/components/src/components/Drawer/Drawer.spec.tsx, packages/components/src/components/GlobalMessage/GlobalMessage.spec.tsx, packages/components/src/components/InlineEdit/InlineEdit.spec.tsx, packages/components/src/components/InternalHeader/InternalHeader.spec.tsx, packages/components/src/components/LocalMessage/LocalMessage.spec.tsx, packages/components/src/components/Modal/Modal.spec.tsx, packages/components/src/components/OverflowMenu/OverflowMenu.spec.tsx, packages/components/src/components/Popover/Popover.spec.tsx, packages/components/src/components/Search/Search.spec.tsx, packages/components/src/components/SplitButton/SplitButton.spec.tsx, packages/components/src/components/Table/SortCell.spec.tsx, packages/components/src/components/Tooltip/Tooltip.spec.tsx, packages/components/src/setupTests.ts, packages/components/src/test/mocks/IntersectionObserver.ts, packages/components/tsconfig.json, packages/components/vite.config.ts, packages/formatting/tsconfig.json, packages/page-generator/package.json, packages/page-generator/tsconfig.json
Ser ut til at vitest gjør at testene i dds-components kjører ~50% raskere! 🚀
=> bytt ut jest med vitest i dds-components

.changeset/rude-buckets-train.md, .gitignore, apps/testapp/app/index.css, apps/testapp/app/root.tsx, apps/testapp/app/routes/banner/$env.tsx, apps/testapp/package.json, package-lock.json, packages/development-utils/.eslintignore, packages/development-utils/.eslintrc.cjs, packages/development-utils/.prettierignore, packages/development-utils/.prettierrc, packages/development-utils/CHANGELOG.md, packages/development-utils/README.md, packages/development-utils/package.json, packages/development-utils/src/EnvironmentBannerProvider.tsx, packages/development-utils/src/index.ts, packages/development-utils/tsconfig.json, packages/development-utils/vite.config.ts
Har lagt til et banner som skal brukes på toppen av skjermbildet for ulike applikasjoner for å indikere hvilket miljø man er i.
=> ELSA1-226 Legger til miljøbanner

.changeset/fast-snakes-give.md, packages/development-utils/src/EnvironmentBannerProvider.tsx
Dette skjedde med blant annet InternalHeader
=> fikse bug hvor miljøbanneren kom bak visse elementer

.changeset/lovely-pets-build.md, package-lock.json, packages/components/src/components/Drawer/Drawer.stories.tsx, packages/components/src/components/Drawer/Drawer.tsx
Legge til ny størrelse på drawer, medium 600px
=> ELSA1-253 New size drawer 

packages/components/src/components/Feedback/CommentComponent.tsx, packages/components/src/components/Feedback/Feedback.spec.tsx, packages/components/src/components/Feedback/Feedback.stories.tsx, packages/components/src/components/Feedback/Feedback.tsx, packages/components/src/components/Feedback/FlexContainer.tsx, packages/components/src/components/Feedback/RatingComponent.tsx
Større iconer for tommler, endring i tekster, midtstilt ved layout column/vertical
=> ELSA1-188: Justeringer ift tilbakemeldinger. 

.changeset/tame-flies-pull.md, packages/components/src/components/Feedback/CommentComponent.tsx, packages/components/src/components/Feedback/Feedback.mdx, packages/components/src/components/Feedback/Feedback.spec.tsx, packages/components/src/components/Feedback/Feedback.stories.tsx, packages/components/src/components/Feedback/Feedback.tsx, packages/components/src/components/Feedback/Feedback.types.tsx, packages/components/src/components/Feedback/FlexContainer.tsx, packages/components/src/components/Feedback/RatingComponent.tsx, packages/components/src/components/Feedback/index.ts, packages/components/src/index.ts
This reverts commit 562215a6a0b88a85366ffa96d0093268d1ce0a99, reversing changes made to 0bba9a91dba102785d6cfd3d71f17d144099c218.
=> Revert "Merge pull request #797 from domstolene/revert-feedback"

.changeset/four-books-press.md, packages/components/src/components/Search/Search.stories.tsx, packages/components/src/components/Search/Search.tsx
=> ELSA1-263 Legger til secondary-type på buttonProps

.changeset/nasty-otters-push.md, packages/components/src/components/Select/Select.styles.ts, packages/components/src/components/Select/Select.tokens.tsx, packages/components/src/components/Select/Select.tsx
Reduserer størrelse på font for at labels ikke skal utvide størrelse av multiselect container
=> Fikser størrelse på <Select isMulti componentSize="tiny" /> labels

packages/components/src/components/Feedback/Feedback.mdx
Legger til avsnitt om teknisk implementasjon på feedback-komponenten:
=> Legger på en beskrivelse om teknisk implementasjon av feedback-komponenten

packages/datepicker/src/Calendar/Calendar.tokens.ts, packages/datepicker/src/Calendar/CalendarCell.tsx, packages/datepicker/src/CalendarPopover.tsx, packages/datepicker/src/DateField/DateField.tsx, packages/datepicker/src/DateField/DateSegment.tsx, packages/datepicker/src/DatePicker.stories.tsx, packages/datepicker/src/DatePicker.tsx, packages/datepicker/src/Introduction.mdx
=> ELSA1-85 DatePicker: Vise kalender i popover

apps/docs/.storybook/main.ts, apps/docs/package.json, package-lock.json, packages/components/src/components/OverflowMenu/OverflowMenu.stories.tsx
Legger til:
- @storybook/addon-storysource for å få se kildekoden til stories. Dette er hjelpsomt for utviklere som vil se kodeeksempler på hvordan komponentene våre brukes.
- @storybook/addon-a11y for å få hjelp med UU-testing.
=> Legge til litt addons til storybook

.changeset/odd-paws-listen.md, packages/components/src/components/ProgressTracker/ProgressTracker.tokens.tsx
=> ELSA1-239 fikse bug i ProgressTracker hvor text zoom gjorde at tall gikk

packages/components/src/components/Tabs/Tabs.mdx
Viser hvordan du kan bruke det nye `width`-attributtet og hvilke verdier som er akseptert.
=> ELSA1-208 legge til mer dokumentasjon for `width` i Tab

packages/components/src/components/date-inputs/DatePicker/Calendar/Calendar.tsx, packages/components/src/components/date-inputs/DatePicker/Calendar/CalendarCell.tsx, packages/components/src/components/date-inputs/DatePicker/CalendarPopover.tsx, packages/components/src/components/date-inputs/DatePicker/DateField/CalendarButton.tsx, packages/components/src/components/date-inputs/DatePicker/DateField/DateField.tsx, packages/components/src/components/date-inputs/DatePicker/DatePicker.tsx, packages/components/src/components/date-inputs/common/DateInput.tsx, stories/examples/Grid.tokens.tsx
Dette fungerer ikke når vi kjører test suite, og fører også til sykliske imports.
=> Fjerne imports fra dds-components inne i dds-components.

.changeset/seven-seals-wash.md, packages/components/src/components/FavStar/FavStar.mdx, packages/components/src/components/FavStar/FavStar.stories.tsx, packages/components/src/components/FavStar/FavStar.tokens.ts, packages/components/src/components/FavStar/FavStar.tsx, packages/components/src/hooks/useCallbackRef.ts, packages/components/src/hooks/useControllableState.ts
Skal brukes der det er behov for å legge til favoritt. Som f.eks. hvis du vil følge en sak i presserom eller favorisere dokumenter i aktørportalene.
=> ELSA1-211  Ny komponent `<FavStar>`

.changeset/lucky-ears-smoke.md, .changeset/quiet-cats-sing.md, packages/components/src/components/Tag/Tag.mdx, packages/components/src/components/Tag/Tag.stories.tsx, packages/components/src/components/Tag/Tag.tokens.tsx, packages/components/src/components/Tag/Tag.tsx
=> ELSA1-236 Ikon på `<Tag>`

.changeset/eighty-singers-return.md, packages/components/src/components/Card/Card.tsx, packages/components/src/components/Card/CardAccordion/CardAccordion.tokens.ts, packages/components/src/components/Card/CardAccordion/CardAccordionHeader.tsx, packages/components/src/components/helpers/styling/focusVisible.tsx
=> ELSA1-225 forbedre fokusmarkering på Card

packages/components/src/components/Button/Button.mdx, packages/components/src/components/Drawer/Drawer.mdx, packages/components/src/components/Drawer/Drawer.stories.tsx, packages/components/src/components/ToggleBar/ToggleBar.stories.tsx, packages/components/src/components/ToggleButton/ToggleButton.mdx, packages/components/src/components/ToggleButton/ToggleButton.stories.tsx, packages/components/src/components/ToggleButton/ToggleButtonGroup.stories.tsx, packages/components/src/components/Tooltip/Tooltip.mdx, packages/components/src/components/Tooltip/Tooltip.stories.tsx, packages/components/src/components/Typography/Caption/Caption.mdx, packages/components/src/components/Typography/Caption/Caption.stories.tsx, packages/components/src/components/Typography/Heading/Heading.mdx, packages/components/src/components/Typography/Heading/Heading.stories.tsx, packages/components/src/components/Typography/Label/Label.mdx, packages/components/src/components/Typography/Label/Label.stories.tsx, packages/components/src/components/Typography/Legend/Legend.mdx, packages/components/src/components/Typography/Legend/Legend.stories.tsx, packages/components/src/components/Typography/Link/Link.mdx, packages/components/src/components/Typography/Link/Link.stories.tsx, packages/components/src/components/Typography/Paragraph/Paragraph.mdx, packages/components/src/components/Typography/Paragraph/Paragraph.stories.tsx, packages/components/src/components/Typography/Typography/Typography.mdx, packages/components/src/components/Typography/Typography/Typography.stories.tsx, packages/components/src/components/VisuallyHidden/VisuallyHidden.mdx, packages/components/src/components/VisuallyHidden/VisuallyHidden.stories.tsx
- En rekke stories var fortsatt i gammel format, inkludert alle Typography-komponenter. Fikser de.
- Fikser mindre feil i docs stories
- Standarisering av oppsettet i docs stories
=> ELSA1-322 skrive om stories til `StoryObj`-format

.changeset/pink-ligers-enjoy.md, packages/components/src/components/InternalHeader/InternalHeader.mdx, packages/components/src/components/InternalHeader/InternalHeader.stories.tsx, packages/components/src/components/InternalHeader/InternalHeader.styles.tsx, packages/components/src/components/InternalHeader/InternalHeader.tokens.tsx, packages/components/src/components/InternalHeader/InternalHeader.tsx
Skjuler også separator hvis det ikke finnes navigasjon eller kontekstmeny.
=> ELSA1-326 Fikser spacing i `<InternalHeader />`

packages/components/src/components/Modal/Modal.stories.tsx
Ikke lukkbar modal rendrer lukkenapp; sørger for at det ikke skjer.
=> Fikser bug i `<Modal />` story

.changeset/fuzzy-impalas-camp.md, .changeset/late-fishes-tap.md, .changeset/silly-flowers-burn.md, packages/components/src/components/LocalMessage/LocalMessage.tokens.tsx, packages/components/src/components/Tag/Tag.stories.tsx, packages/components/src/components/Tag/Tag.tokens.tsx, packages/components/src/components/Tag/Tag.tsx
- Legger til `strong` variant av `<Tag />` for alle `purpose`.
- Justerer på avstander i komponenten.
- Gjør rammefargen lik i både `<Tag />` og `<LocalMessage />`.
=> ELSA1-312 Legger til strong variant av `<Tag />`

.changeset/sharp-socks-visit.md, packages/components/src/components/Typography/Heading/Heading.tsx
Oppdaterer default styling i `<Heading />` for nivåene 2, 3, 4 og 5.
=> ELSA1-336 Default styling i `<Heading />`

README.md, packages/components/README.md, packages/components/src/components/InternalHeader/InternalHeader.stories.tsx, packages/components/src/components/Typography/Label/Label.mdx, packages/development-utils/README.md, stories/Introduction.stories.mdx
Offskrift på bruk av changeset og små endringer i docs og READMEs ellers.
=> ELSA1-317 Changeset docs

.changeset/lovely-coins-punch.md, packages/components/src/components/InlineButton/InlineButton.mdx, packages/components/src/components/InlineButton/InlineButton.spec.tsx, packages/components/src/components/InlineButton/InlineButton.stories.tsx, packages/components/src/components/InlineButton/InlineButton.tsx, packages/components/src/components/InlineButton/index.ts, packages/components/src/index.ts
Den ser ut som en lenke og brukes i mengdetekst.
=> Legger til ny komponent: `<InlineButton/>`.

.changeset/lovely-avocados-juggle.md, packages/components/src/components/Typography/Link/Link.stories.tsx, packages/components/src/components/Typography/Link/Link.tsx, packages/components/src/components/Typography/Typography/Typography.styles.ts, packages/components/src/components/Typography/Typography/Typography.tsx
Fikser at ikon som vises `<Link external />` ikke overlapper med annet innhold
=> ELSA1-344 Fikser ikon i `<Link external />`

.changeset/chilly-shirts-train.md, .changeset/two-wolves-doubt.md, packages/components/src/components/Fieldset/Fieldset.mdx, packages/components/src/components/Fieldset/Fieldset.spec.tsx, packages/components/src/components/Fieldset/Fieldset.stories.tsx, packages/components/src/components/Fieldset/Fieldset.tsx, packages/components/src/components/Fieldset/index.ts, packages/components/src/components/Typography/Legend/Legend.mdx, packages/components/src/components/Typography/Legend/Legend.tsx, packages/components/src/components/Typography/Typography.tokens.tsx, packages/components/src/components/Typography/Typography/Typography.styles.ts, packages/components/src/components/Typography/Typography/Typography.utils.ts, packages/components/src/index.ts
Fikser også padding i `<Legend />`
=> Ny komponent: `<Fieldset />`

.changeset/big-rockets-carry.md, packages/components/src/components/Button/Button.spec.tsx, packages/components/src/components/ButtonGroup/ButtonGroup.mdx, packages/components/src/components/ButtonGroup/ButtonGroup.spec.tsx, packages/components/src/components/ButtonGroup/ButtonGroup.stories.tsx, packages/components/src/components/ButtonGroup/ButtonGroup.tsx, packages/components/src/components/ButtonGroup/index.ts, packages/components/src/components/Stack/Stack.mdx, packages/components/src/components/Stack/Stack.stories.tsx, packages/components/src/index.ts
Brukes til gruppering av flere relaterte `<Button />`.
=> ELSA1-109 Ny komponent: `<ButtonGroup />`.

.changeset/witty-spies-warn.md, packages/components/src/components/Button/Button.styles.tsx
Fjerner hover og active-styling i `<Button />` ved `loading`.
=> ELSA1-360 Styling i `<Button />` ved `loading`

.changeset/chilled-bags-shave.md, packages/components/src/components/Icon/icons.stories.tsx, packages/components/src/components/Select/CustomSelect.stories.tsx, packages/components/src/components/Select/Select.tsx, packages/components/src/components/Select/SelectComponents.tsx, packages/components/src/components/SelectionControl/RadioButton/RadioButtonGroup.stories.tsx
Støtte for `data-testid` i `<Select />` for lettere testing.
=> ELSA1-366 `data-testid` i `<Select />`

.changeset/thirty-rabbits-stare.md, packages/components/src/components/FileUploader/FileUploader.stories.tsx, packages/components/src/components/FileUploader/FileUploader.tsx, turbo.json
=> ELSA1-375 Legger til manglende props for labels i FileUploader

.storybook/preview-head.html, packages/app-shell/src/AppShell/AppShell.mdx, packages/app-shell/src/AppShell/AppShell.stories.tsx, packages/components/src/components/BackLink/BackLink.stories.tsx, packages/components/src/components/InternalHeader/InternalHeader.mdx, packages/components/src/components/InternalHeader/InternalHeader.stories.tsx, packages/components/src/components/OverflowMenu/OverflowMenu.mdx, packages/components/src/components/OverflowMenu/OverflowMenu.stories.tsx, packages/components/src/components/Popover/Popover.mdx, packages/components/src/components/Popover/Popover.stories.tsx, packages/components/src/components/SplitButton/SplitButton.stories.tsx, packages/components/src/components/date-inputs/DatePicker/DatePicker.mdx, packages/components/src/components/date-inputs/DatePicker/DatePicker.stories.tsx
- høyde i noen komponenter
- spacing for docs story
=> Storybook story justeringer

.changeset/real-plums-sell.md, packages/components/src/components/FileUploader/File.tsx, packages/components/src/components/FileUploader/FileUploader.module.css, packages/components/src/components/FileUploader/FileUploader.tsx
Justeringer på mindre ting:
- ikon som viser om filen er gyldig
- spacing under knapp
- border-radius på containere
- border på filer i lista
- setter typografi for tekst
=> ELSA1-396 Fikser styling i `<FileUploader>`

.storybook/preview-head.html, packages/app-shell/stories/changelog.mdx, packages/components/src/components/Typography/Typography/Typography.mdx, packages/components/src/styles/dds-tokens.css, packages/tokens/README.md
Oppdaterer storybook docs, readme, changelog med informasjon som stemmer med nyeste versjon. Oppdaterer styling i docs til å stemme med nye tokens og design ellers.
=> ELSA1-400 Oppdaterer docs med ny versjon

README.md
Inkluderer en seksjon om publisering til info for bidragsytere.
=> ELSA1-402 Oppdaterer README med publisering

.changeset/purple-toys-join.md, packages/components/src/components/Select/NativeSelect/NativeSelect.mdx, packages/components/src/components/Select/NativeSelect/NativeSelect.module.css, packages/components/src/components/Select/NativeSelect/NativeSelect.spec.tsx, packages/components/src/components/Select/NativeSelect/NativeSelect.stories.tsx, packages/components/src/components/Select/NativeSelect/NativeSelect.tsx, packages/components/src/components/Select/NativeSelect/index.ts, packages/components/src/components/Select/Select.tsx, packages/components/src/components/Select/index.ts, packages/components/src/components/date-inputs/common/DateInput.module.css, packages/components/src/components/date-inputs/common/DateInput.tsx, packages/components/src/components/helpers/Input/Input.module.css
Brukes når det trengs nativ `<select>` istedenfor komponenten `<Select>` som er custom bygd.
=> ELSA1-367 Ny komponent: `<NativeSelect />`

.changeset/config.json
Changeset skal bumpe peer dependents kun når peerDependencies er utenfor range.
=> peerDependencies bump begrensning

packages/tokens/dds/tokens/Base.json, packages/tokens/dds/tokens/font/font.json
Egne tokens for typografistilene våre
=> Supplerende tokens for paragraph spacing, font style og letter spacing

.changeset/poor-pans-nail.md, packages/components/src/components/Typography/typographyStyles.module.css, packages/tokens/dds/build/css/ddsTokens.css, packages/tokens/dds/build/js/ddsTokens.ts, packages/tokens/dds/build/scss/_ddsTokens.scss, packages/tokens/dds/tokens/$themes.json, packages/tokens/dds/tokens/Semantic.json
Slik at brukere kan ta i bruk visited link prop for dds-link på inverse surfaces
=> New color token for visited link on inverse surface

.changeset/smooth-crabs-watch.md, packages/components/src/components/Typography/typographyStyles.module.css
Justerer på tykkelse og offsett for `text-decoration` i `<Link>`.
=> ELSA1-419 justerer på `text-decoration` i `<Link>`

stories/Playground/FormComponentsTesting.stories.tsx
Story for å teste at komponenter ser likt ut.
=> Legger til story for testing av skjemakomponenter

.changeset/popular-drinks-smell.md, packages/components/src/components/Card/Card.module.css
Endrer CSS `border-radius` i `<Card>` til `--dds-border-radius-surface`.
=> ELSA1-410 Card `border-radius`

.changeset/beige-tips-refuse.md, packages/components/src/components/ProgressBar/ProgressBar.mdx, packages/components/src/components/ProgressBar/ProgressBar.module.css, packages/components/src/components/ProgressBar/ProgressBar.spec.tsx, packages/components/src/components/ProgressBar/ProgressBar.stories.tsx, packages/components/src/components/ProgressBar/ProgressBar.tsx, packages/components/src/components/ProgressBar/index.ts, packages/components/src/components/helpers/Input/Input.types.tsx, packages/components/src/index.ts
Den kan brukes til å vise progresjon av en prosess,rendering, nedlasting eller opplasting.
=> ELSA1-406 Ny komponent: ProgressBar

.changeset/cyan-walls-know.md, packages/components/src/components/ToggleButton/ToggleButton.module.css
Setter farge på border i `<ToggleButton>` til `--dds-color-border-default`.
=> ELSA1-463 Setter farge på border i `<ToggleButton>`

.changeset/afraid-sloths-peel.md, packages/components/src/components/Feedback/Feedback.module.css
Fargen på ikon i knappene bruke feil token. Setter den til riktig.
=> ELSA1-464 Fikser farge på ikoner i `<Feedback>`

.changeset/ninety-ways-tease.md, .changeset/stale-guests-boil.md, packages/components/src/components/PhoneInput/PhoneInput.mdx, packages/components/src/components/PhoneInput/PhoneInput.module.css, packages/components/src/components/PhoneInput/PhoneInput.spec.tsx, packages/components/src/components/PhoneInput/PhoneInput.stories.tsx, packages/components/src/components/PhoneInput/PhoneInput.tsx, packages/components/src/components/PhoneInput/constants.ts, packages/components/src/components/PhoneInput/index.ts, packages/components/src/components/Search/Search.tsx, packages/components/src/components/Select/NativeSelect/NativeSelect.module.css, packages/components/src/components/Select/NativeSelect/NativeSelect.stories.tsx, packages/components/src/components/Select/NativeSelect/NativeSelect.tsx, packages/components/src/components/Select/SelectComponents.tsx, packages/components/src/components/TextInput/TextInput.tsx, packages/components/src/components/helpers/Input/Input.module.css, packages/components/src/hooks/useCombinedRefs.tsx, packages/components/src/index.ts
Består av en nedtrekksliste med landskoder og `<input type="tel">`.
Fikser i sammen slengen typings for `NativeSelectProps`, da de tillatet native `<input>` props; skal være `<select>` props istedet.
=> ELSA1-283 Ny komponent: PhoneInput

.changeset/green-ducks-yell.md, packages/formatting/src/bank/formatBankAccountNumber.test.ts, packages/formatting/src/bank/formatBankAccountNumber.ts, packages/formatting/src/bank/index.ts, packages/formatting/src/index.ts
Legger til funksjon for formattering av bankkontonummer: `formatBankAccountNumber()`.
=> ELSA1-471 Funksjon for formattering av kontonummer

packages/components/src/components/Divider/Divider.stories.tsx
Bakgrunn for `onInverse` variant skal være `dds-color-surface-inverse-default`.
Før:
Etter:
=> ELSA1-478 Fikser bakgrunn i `Divider` story

.changeset/thirty-pumpkins-tan.md, packages/components/src/components/InputMessage/InputMessage.module.css
Legger `--dds-border-radius-surface` på nedre hjørner.
=> ELSA1-495 Fikser `border-radius` i `<InputMessage>`

.changeset/lovely-items-march.md, packages/components/src/components/PhoneInput/PhoneInput.tsx, packages/components/src/components/PhoneInput/constants.ts
Fikser alfabetisk sortering + oppdaterer "Hviterussland" til "Belarus".
=> ELSA1-498 Fikser sortering i `<PhoneInput>`

.changeset/new-ghosts-rest.md, packages/components/src/components/Feedback/CommentComponent.tsx, packages/components/src/components/Feedback/Feedback.module.css, packages/components/src/components/Feedback/Feedback.tsx, packages/components/src/components/Feedback/Feedback.types.tsx, packages/components/src/components/Feedback/RatingComponent.tsx, packages/components/src/components/Feedback/utils.tsx
Refaktorerer litt i samme slengen, da det har vært mange små feil i forhold til skissene. Lettere å holde varianter av ikonet ett sted.
=> ELSA1-484 Fikser ikonstørrelser i `<Feedback>`

.changeset/early-readers-accept.md, packages/components/src/components/Card/Card.module.css
Endrer fargen til `var(--dds-color-border-subtle)`.
=> ELSA1-455 Endrer farge på border i `<Card>`

packages/dds-components/src/components/Popover/Popover.tsx
This reverts commit 0ab1ce6304671c3f5df738649953606a3493cd25.
=> Revert "Popover scroll debug"

.changeset/thin-candles-pull.md, packages/dds-components/src/components/BackLink/BackLink.mdx, packages/dds-components/src/components/BackLink/BackLink.tsx
For lettere bruk i Next.js. Skal endre til en polymorfisk løsning ved migrering til React 19.
=> ELSA1-506 Støtte for `OnClick` i `<BackLink>`

packages/dds-components/src/components/Search/Search.mdx, packages/dds-components/src/components/TextArea/TextArea.mdx, packages/dds-components/src/components/TextInput/TextInput.mdx
Anbefalinger på maks antall tegn i noen input-komponenter, for å evt unngå at en løsning knekker.
=> ELSA1-503 Retningslinjer på maks lengde input

.changeset/brown-cups-smile.md, packages/dds-components/src/components/PhoneInput/PhoneInput.stories.tsx, packages/dds-components/src/components/SelectionControl/RadioButton/RadioButton.spec.tsx, packages/dds-components/src/components/SelectionControl/RadioButton/RadioButton.tsx, packages/dds-components/src/components/SelectionControl/RadioButton/RadioButton.types.tsx, packages/dds-components/src/components/SelectionControl/RadioButton/RadioButtonGroup.stories.tsx, packages/dds-components/src/components/SelectionControl/RadioButton/RadioButtonGroup.tsx, packages/dds-components/src/components/SelectionControl/RadioButton/RadioButtonGroupContext.tsx
Slik at man kan bruke ukontrollert state med initiell verdi.
Refaktorering og opprydding i samme slengen.
=> ELSA1-439 Støtte for `defaultValue` prop i `<RadioButtonGroup>`

packages/dds-components/src/components/Drawer/Drawer.tsx, packages/dds-components/src/components/Modal/Modal.mdx, packages/dds-components/src/components/Modal/Modal.tsx, packages/dds-components/src/components/Select/NativeSelect/NativeSelect.stories.tsx, packages/dds-components/src/components/Select/Select.mdx
Komponentene som bruker React Portal hadde ikke oppdaterte docs, fikser.
=> Fikser docs relaterte til React Portal

.npmrc, package.json, pnpm-lock.yaml
- oppdaterer nøstede dependencies
- oppdaterer pnpm
=> ELSA1-502 Fikser vulnerabilities

.changeset/two-emus-occur.md, packages/dds-components/src/components/Toggle/Toggle.mdx, packages/dds-components/src/components/Toggle/Toggle.module.css, packages/dds-components/src/components/Toggle/Toggle.spec.tsx, packages/dds-components/src/components/Toggle/Toggle.stories.tsx, packages/dds-components/src/components/Toggle/Toggle.tsx, packages/dds-components/src/components/Toggle/index.ts, packages/dds-components/src/index.ts
=> ELSA1-28 Ny komponent: Toggle

.changeset/forty-impalas-drive.md, packages/dds-components/src/components/OverflowMenu/OverflowMenu.module.css, packages/dds-components/src/components/OverflowMenu/OverflowMenu.stories.tsx, packages/dds-components/src/components/OverflowMenu/OverflowMenu.types.tsx, packages/dds-components/src/components/OverflowMenu/components/OverflowMenuButton.tsx, packages/dds-components/src/components/OverflowMenu/components/OverflowMenuLink.tsx, packages/dds-components/src/components/OverflowMenu/components/OverflowMenuSpan.tsx
Slik at man kan bruke `danger`-farge på elementer i menyen
=> ELSA1-523 Støtte for `purpose`-prop for `<li>` i `OverflowMenu`

PULL_REQUEST_TEMPLATE.md
=> ELSA1-532 PR mal

stories/Tokens/Tokens.stories.tsx, stories/Tokens/TypographyBase.stories.tsx, stories/Tokens/utils/SpacingGenerator.tsx, stories/Tokens/utils/TypographyGenerator.tsx, stories/Tokens/utils/functions.tsx, stories/Tokens/utils/index.ts
=> ELSA1-538 Tokens oversikt for spacing og paragraph spacing

.changeset/hip-moons-move.md, packages/dds-components/src/components/Tabs/AddTabButton.tsx, packages/dds-components/src/components/Tabs/TabList.tsx, packages/dds-components/src/components/Tabs/Tabs.context.tsx, packages/dds-components/src/components/Tabs/Tabs.mdx, packages/dds-components/src/components/Tabs/Tabs.stories.tsx, packages/dds-components/src/components/Tabs/Tabs.tsx, packages/dds-components/src/components/Tabs/index.tsx
Støttet via `addTabButtonProps` prop.
=> ELSA1-178 Støtte for "Legg til fane"-knapp i `<Tabs>`

CONTRIBUTING.md, package.json
Det er vanlig at man vil kjøre tester for en enkel komponent. Lager custom script på det og oppdaterer `CONTRIBUTING.md`.
=> ELSA1-549 Custom test script for komponenter

packages/dds-components/src/components/BackLink/BackLink.mdx, packages/dds-components/src/components/Typography/Link/Link.mdx
=> ELSA1-555 Docs på bruk av lenker i `Next.js`

.github/workflows/pull-request.yml
Legger til permissions; Fikser "Workflow does not contain permissions" issue etter Code Scan.
=> ELSA1-559 Fikser permissions i `pull-request.yml`

packages/dds-components/package.json, packages/development-utils/package.json, pnpm-lock.yaml
=> ELSA1-566 Fjerner ubrukte dependencies

.changeset/nine-lines-think.md, packages/dds-components/src/components/helpers/Paper/Paper.tsx
=> ELSA1-569 Fikser bug der `<Drawer>` fikk border

.changeset/chatty-lights-change.md, packages/development-utils/package.json
=> ELSA1-572 Eksporter css-fil for development-utils

.changeset/chatty-dryers-find.md
=> Fikser typo i release notes

.changeset/metal-tables-fix.md, packages/dds-components/src/components/CookieBanner/CookieBanner.mdx, packages/dds-components/src/components/CookieBanner/CookieBanner.module.css, packages/dds-components/src/components/CookieBanner/CookieBanner.spec.tsx, packages/dds-components/src/components/CookieBanner/CookieBanner.stories.tsx, packages/dds-components/src/components/CookieBanner/CookieBanner.tsx, packages/dds-components/src/components/CookieBanner/CookieBannerCheckbox.tsx, packages/dds-components/src/components/CookieBanner/index.ts, packages/dds-components/src/components/SelectionControl/Checkbox/Checkbox.tsx, packages/dds-components/src/components/SelectionControl/RadioButton/RadioButton.tsx, packages/dds-components/src/components/SelectionControl/SelectionControl.module.css, packages/dds-components/src/components/layout/common/layout.module.css, packages/dds-components/src/index.ts
Komponent med valgfritt innhold; støtter props for typisk innhold for standardisert implementasjon.
=> ELSA1-595 Ny komponent: `<CookieBanner>`

stories/Tokens/NotExposed.stories.tsx, stories/Tokens/utils/BorderRadiusGenerator.tsx
Legger til en story som vise en tabell med basetokens. Til bruk som embedded i dokumentasjonen.
=> ELSA1-580 Border radius basetokens i Storybook

package.json, pnpm-lock.yaml
Fikser unmet peers i samme slengen.
=> ELSA1-563 fikser vulnerabilities

.changeset/few-heads-work.md, packages/dds-components/src/components/SplitButton/SplitButton.tsx
…app for å åpne liste med flere valg trykkes
_Denne PRen endrer..._
=> ELSA1-613 - SplitButton: Sett type="button" for å hindre at skjema submittes når knapp for å åpne liste med flere valg trykkes

.github/composite-actions/install/action.yml, package.json
=> ELSA1-623 Oppdaterer Node til v24

CONTRIBUTING.md
- Endrer rekkefølge på Volta-installasjonene, da Node bør være på plass før pnpm
- Legger til kjøring av build, slik at Storybook kan finne `index.css` i dist-mappa.
=> Oppdaterer `CONTRIBUTING.md`

stories/Tokens/utils/ShadowsGenerator.tsx
Det er ikke viktig å ha med basefarge, fjerner den for renere tabell.
=> ELSA1-631 Fjerner base i tokens-oversikt for skygger

.github/dependabot.yml
=> Fikser Typescript group i dependabot YAML

.changeset/chubby-shirts-brush.md, packages/dds-components/src/components/Toggle/Toggle.mdx, packages/dds-components/src/components/Toggle/Toggle.module.css, packages/dds-components/src/components/Toggle/Toggle.stories.tsx
Den hakket litt, utbedrer CSS. Migrerer komponenten til `<Tabs>` visning i docs i samme slengen.
=> ELSA1-672 Utbedrer animasjon i `<Toggle>`

.github/composite-actions/install/action.yml
=> ELSA1 Fikser `chromatic.yml` error der den ikke fant `pnpm`

.github/workflows/chromatic.yml
Unngår duplisering i `chromatic.yml`
=> ELSA1 Kjører `actions/setup-node` kun i `action.yml`
